unpackaged/main/default/objects/ffps_forterro__ServiceRequest__c/ffps_forterro__ServiceRequest__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ffps_forterro__ServiceRequest__c/fields/ffps_forterro__Type__c.field-meta.xml
<CustomField>
    <fullName>ffps_forterro__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSP</fullName>
                <default>true</default>
                <label>FSP</label>
            </value>
            <value>
                <fullName>Ad Hoc</fullName>
            </value>
            <value>
                <fullName>SupportBillable</fullName>
                <label>Support - Billable</label>
            </value>
            <value>
                <fullName>SupportCredited</fullName>
                <label>Support - Extended Support (Credited)</label>
            </value>
            <value>
                <fullName>smallrequest</fullName>
                <label>Small Request</label>
            </value>
            <value>
                <fullName>Small Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ffps_forterro__ServiceRequest__c/fields/Trigger_Ongoing_Task__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Ongoing_Task__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Updated by FLOW. Used to create an assignment, and task from a customer request.</description>
    <label>Trigger Ongoing Task</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/TriggerOngoingTaskForServiceRequestTest.cls
@isTest
public class TriggerOngoingTaskForServiceRequestTest 
{
    @isTest static void MainTest()
    {
        ffps_forterro__ServiceRequest__c req = new ffps_forterro__ServiceRequest__c(
            Trigger_Ongoing_Task__c = false,
            ffps_forterro__Type__c = 'SupportBillable'
        );
        insert req;

        Test.startTest();

        TriggerOngoingTaskForServiceRequestBatch batch = new TriggerOngoingTaskForServiceRequestBatch();
        Database.executeBatch( batch, 1 );

        Test.stopTest();

        req = [Select Id, Trigger_Ongoing_Task__c from ffps_forterro__ServiceRequest__c where Id = :req.Id];
        system.assert( req.Trigger_Ongoing_Task__c == true );
    }

    @isTest static void ScheduleTest()
    {
        TriggerOngoingTaskForServiceRequestBatch.scheduleEveryFiveMinutes();
    }
}