unpackaged/main/default/objects/Deleted_Task_Time_Split__c/Deleted_Task_Time_Split__c.object-meta.xml
<CustomObject>
    <label>Deleted Task Time Split</label>
    <nameField>
        <displayFormat>DTTS{000000}</displayFormat>
        <label>Deleted Task Time Split Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deleted Task Time Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Deleted_Task_Time_Split__c/fields/Revoke_Reason__c.field-meta.xml
<CustomField>
    <fullName>Revoke_Reason__c</fullName>
    <label>Revoke Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Deleted_Task_Time_Split__c/fields/Revoke_State__c.field-meta.xml
<CustomField>
    <fullName>Revoke_State__c</fullName>
    <label>Revoke State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Granted</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Deleted_Task_Time_Split__c/fields/Revoked_By__c.field-meta.xml
<CustomField>
    <fullName>Revoked_By__c</fullName>
    <label>Revoked By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Deleted_Task_Time_Split__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Deleted_Task_Time_Split__c/fields/SyncDate__c.field-meta.xml
<CustomField>
    <fullName>SyncDate__c</fullName>
    <label>SyncDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Deleted_Task_Time_Split__c/fields/Task_Time_Split_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Time_Split_Id__c</fullName>
    <externalId>true</externalId>
    <label>Task Time Split Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Deleted_Task_Time_Split__c/fields/Timecard__c.field-meta.xml
<CustomField>
    <fullName>Timecard__c</fullName>
    <label>Timecard</label>
    <referenceTo>pse__Timecard_Header__c</referenceTo>
    <relationshipLabel>Deleted Task Time Splits</relationshipLabel>
    <relationshipName>Deleted_Task_Time_Splits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Region__c/pse__Region__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__RegionHelp</customHelpPage>
    <description>An entity that represents a geographic area in which you do business. Regions are organized as an independent hierarchy determined by the Parent Region field, with parent and child records of the same type. Every region in the hierarchy may contain projects, resources (contacts), and other objects. The hierarchy allows roll-ups of revenue, cost, and time totals.</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Region__c/fields/BU_Code__c.field-meta.xml
<CustomField>
    <fullName>BU_Code__c</fullName>
    <description>Used in Integration with ERP.</description>
    <label>BU Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/pse__Timecard_Header__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__TimecardHelp</customHelpPage>
    <description>Records the hours and days worked by a resource in a given week. Timecards are associated with a project and may also be logged against an assignment or milestone, or against one or more project tasks. Resources can submit multiple timecards on the Timecard Entry page, accessed by clicking either “Log a Timecard - New UI” or “Log a Timecard with Task Time” on the PSA Links sidebar (depending on whether your organization logs time against project tasks). This object is named Timecard_Header (API name pse__Timecard_Header__c) and has a master-detail relationship with timecard splits.</description>
    <label>Timecard</label>
    <nameField>
        <displayFormat>TCH-{MM}-{DD}-{YYYY}-{000000}</displayFormat>
        <label>Timecard Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Revoke_Reason__c.field-meta.xml
<CustomField>
    <fullName>Revoke_Reason__c</fullName>
    <description>Used by Plan D Integration.</description>
    <label>Revoke Reason</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <description>Used by ERP Integration (Plan D).</description>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Extracted</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Failed Sync</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Pending Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DeletedTaskTimeAPI.cls
@RestResource(urlMapping='/tasktimeapi/deletedtasktimes/*')
global with sharing class DeletedTaskTimeAPI 
{
    public class AppException extends Exception {}

    private final static String BASE_URI = '/tasktimeapi/deletedtasktimes/';
    private final static integer MAX_RECORDS = 1000;

    global class DeletedTimeEntry
    {
        public Id timeEntryId;
        public Id deletedTimeEntryId;
        public string revokeState;
        public DateTime syncDate;
        public string syncState;
        public string revokeReason;
        public string revokedBy;

        global DeletedTimeEntry()
        {
        }

        public DeletedTimeEntry( Deleted_Task_Time_Split__c split )
        {
            timeEntryId = split.Task_Time_Split_Id__c;
            deletedTimeEntryId = split.Id;
            revokeState = split.Revoke_State__c;
            syncDate = split.SyncDate__c;
            syncState = split.Sync_Status__c;
            revokeReason = split.Revoke_Reason__c;
            revokedBy = split.Revoked_By__c;
        }
    }

    global class DeletedTimeEntryUpdate
    {
        public Id timeEntryId;
        public string revokeState;
        public DateTime syncDate;
        public string syncState;
    }

    @HttpGet
    global static void HandleGet()
    {
        try
        {
            RestRequest req = RestContext.request;
            string context = req.requestURI.substring( req.requestURI.indexOf(BASE_URI) + BASE_URI.length() );

            List<pse__Region__c> regions = [Select Id from pse__Region__c where BU_Code__c = :context];
            if( regions.size() == 0 )
            {
                throw new AppException( 'Failed to find business unit code ' + context );
            }

            List<DeletedTimeEntry> timeEntries = new List<DeletedTimeEntry>();

            for( Deleted_Task_Time_Split__c split :
                [Select
                    Id, 
                    Task_Time_Split_Id__c,
                    Sync_Status__c,
                    SyncDate__c,
                    Revoke_Reason__c,
                    Revoked_By__c,
                    Revoke_State__c
                From
                    Deleted_Task_Time_Split__c
                Where
                    Sync_Status__c = 'New' and
                    Timecard__r.pse__Project__r.pse__Region__r.BU_Code__c = :context
                Limit
                    :MAX_RECORDS] )
            {
                DeletedTimeEntry entry = new DeletedTimeEntry( split );
                timeEntries.add( entry );
            }

            RestAPIHelper.SetRestReturn( timeEntries, false );
        }
        catch( Exception ex )
        {
            RestAPIHelper.SetRestError( 400, 'BAD_REQUEST', new List<string>{ ex.getMessage() } );
        }
    }

    @HttpPost
    global static void HandlePost( DeletedTimeEntryUpdate[] timeEntries )
    {
        Savepoint savePoint = Database.setSavepoint();

        try
        {
            Map<Id,DeletedTimeEntryUpdate> timeEntryMap = new Map<Id,DeletedTimeEntryUpdate>();
            for( DeletedTimeEntryUpdate entry : timeEntries )
            {
                timeEntryMap.put( entry.timeEntryId, entry );
            }

            Map<string,Deleted_Task_Time_Split__c> splits = new Map<string,Deleted_Task_Time_Split__c>();

            for( Deleted_Task_Time_Split__c split :
                [Select 
                    Id, 
                    Task_Time_Split_Id__c, 
                    Sync_Status__c, 
                    SyncDate__c,
                    Revoke_State__c
                from 
                    Deleted_Task_Time_Split__c 
                where
                    Task_Time_Split_Id__c in :timeEntryMap.keySet()] )
            {
                splits.put( split.Task_Time_Split_Id__c, split );
            }

            List<Deleted_Task_Time_Split__c> splitsToUpdate = new List<Deleted_Task_Time_Split__c>();
            List<string> errors = new List<string>();

            for( DeletedTimeEntryUpdate entry : timeEntries )
            {
                if( !splits.containsKey( entry.timeEntryId ) )
                {
                    errors.add( 'Entry ' + entry.timeEntryId + ' not found' + timeEntryMap.keySet() );
                    continue;
                }

                Deleted_Task_Time_Split__c split = splits.get( entry.timeEntryId );
                split.Sync_Status__c = entry.syncState;
                split.Revoke_State__c = entry.revokeState;

                if( entry.syncDate != null )
                {
                    split.SyncDate__c = entry.syncDate;
                }

                if( entry.syncState == 'Synced' && split.SyncDate__c == null )
                {
                    split.SyncDate__c = system.now();
                }

                splitsToUpdate.add( split );
            }

            if( errors.size() > 0 )
            {
                RestAPIHelper.SetRestError( 400, 'BAD_REQUEST', errors );
            }
            else
            {
                update splitsToUpdate;
                RestAPIHelper.SetRestReturn( timeEntryMap.size(), true );
            }
        }
        catch( Exception ex )
        {
            RestAPIHelper.SetRestError( 400, 'BAD_REQUEST', new List<string>{ ex.getMessage() } );
            Database.rollback( savePoint );
        }
    }
}