unpackaged/main/default/objects/Data_Import_Results__c/Data_Import_Results__c.object-meta.xml
<CustomObject>
    <label>Data Import Result</label>
    <nameField>
        <displayFormat>DIR{000000}</displayFormat>
        <label>Data Import Results Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Import Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Data_Import_Results__c/fields/Errors__c.field-meta.xml
<CustomField>
    <fullName>Errors__c</fullName>
    <label>Errors</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/pse__Assignment__c/pse__Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Assignment__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Assignment__c/fields/Role_Budget__c.field-meta.xml
<CustomField>
    <fullName>Role_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Role Budget</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Role_Budget__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.pse__Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.pse__Role__c</field>
            <operation>equals</operation>
            <valueField>Role_Budget__c.Role__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Role_Budget__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Budget__c/pse__Budget__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__BudgetHelp</customHelpPage>
    <description>A budgeted amount for a PSA project. Represents, depending on its type, customer purchase orders, internal budgets, outbound vendor purchase orders, or work orders, as well as change requests to these records. It may also contain a separate expense budget amount and specified pre-bill amount.</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Budget__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Milestone__c/pse__Milestone__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__MilestoneHelp</customHelpPage>
    <description>A target event used to track project progress. In Time and Materials (T&amp;M) projects, individual milestone records are generally not billable, whereas in Fixed Price or mixed projects all or some generally are. You can group together timecards and expenses, submitted by assigned resources, with milestones on the same project, or associate milestones with a fixed external cost. Milestones have a linear (non-hierarchical) relationship with one another.</description>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Milestone__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Miscellaneous_Adjustment__c/pse__Miscellaneous_Adjustment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__MiscellaneousAdjustmentHelp</customHelpPage>
    <description>Use miscellaneous adjustments to correct errors in data entry or adjust transactions. When you create a miscellaneous adjustment, PSA creates a number of related transactions of a specific category (for example, Pass-Through Ready-to-Bill Revenue) and amount. A miscellaneous adjustment is applied to a project and its related roll-ups to region, practice, and group. Miscellaneous adjustments roll up to actuals fields depending on settings you control in the Actuals configuration group.</description>
    <label>Miscellaneous Adjustment</label>
    <nameField>
        <label>Miscellaneous Adjustment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Miscellaneous Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Project_Task__c/pse__Project_Task__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Project_Task__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Project that the Task is a part of.</description>
    <inlineHelpText>You do not have to define the Project field when creating a child task. The Project field auto-populates from the parent task and overwrites any entered value.</inlineHelpText>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task__c/fields/Role_Budget__c.field-meta.xml
<CustomField>
    <fullName>Role_Budget__c</fullName>
    <inlineHelpText>Role Budget Reference</inlineHelpText>
    <label>Role Budget Reference</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/pse__Resource_Request__c/pse__Resource_Request__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ResourceRequestHelp</customHelpPage>
    <description>Operating as a means of asking for resources to staff an existing or planned project, resource requests collect information to help users responsible for staffing and assignment creation to choose the right resource. The user requesting the resource (e.g., project manager or sales professional) may create a resource request from an opportunity or project, or generate them based on project tasks and project task assignments. Held resource requests, or “soft bookings”, occur when a named resource has been reserved for a project or opportunity, but not yet assigned to the project.</description>
    <label>Resource Request</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Resource Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Resource_Request__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Resource Requests</relationshipLabel>
    <relationshipName>Resource_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Resource_Request__c/fields/Role_Budget__c.field-meta.xml
<CustomField>
    <fullName>Role_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Role Budget</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Role_Budget__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.pse__Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.pse__Resource_Role__c</field>
            <operation>equals</operation>
            <valueField>Role_Budget__c.Role__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Role_Budget__c</referenceTo>
    <relationshipLabel>Resource Requests</relationshipLabel>
    <relationshipName>Resource_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/pse__Timecard_Header__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__TimecardHelp</customHelpPage>
    <description>Records the hours and days worked by a resource in a given week. Timecards are associated with a project and may also be logged against an assignment or milestone, or against one or more project tasks. Resources can submit multiple timecards on the Timecard Entry page, accessed by clicking either “Log a Timecard - New UI” or “Log a Timecard with Task Time” on the PSA Links sidebar (depending on whether your organization logs time against project tasks). This object is named Timecard_Header (API name pse__Timecard_Header__c) and has a master-detail relationship with timecard splits.</description>
    <label>Timecard</label>
    <nameField>
        <displayFormat>TCH-{MM}-{DD}-{YYYY}-{000000}</displayFormat>
        <label>Timecard Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/pse__Assignment__c.field-meta.xml
<CustomField>
    <fullName>pse__Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>pse__Assignment__c.pse__Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.pse__Project__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>pse__Assignment__c</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/pse__Milestone__c.field-meta.xml
<CustomField>
    <fullName>pse__Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Milestone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>pse__Milestone__c.pse__Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.pse__Project__c</valueField>
        </filterItems>
        <infoMessage>Only milestones for the same project are shown. To display all milestones, click Show all results.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>pse__Milestone__c</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Role_Budget__c/Role_Budget__c.object-meta.xml
<CustomObject>
    <label>Role Budget</label>
    <nameField>
        <displayFormat>RB-{00000}</displayFormat>
        <label>Role Budget</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Role_Budget__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Role_Budget__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Role Budgets</relationshipLabel>
    <relationshipName>Role_Budgets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Staging_Project__c/Staging_Project__c.object-meta.xml
<CustomObject>
    <description>Used for Data Migration</description>
    <label>Staging Project</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Staging Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Staging_Project__c/fields/Import_Status__c.field-meta.xml
<CustomField>
    <fullName>Import_Status__c</fullName>
    <label>Import Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Base Import Complete</fullName>
            </value>
            <value>
                <fullName>Parents Associated</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Staging_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Staging Projects</relationshipLabel>
    <relationshipName>Staging_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ClearStagingDataBatch.cls
public class ClearStagingDataBatch implements Database.Batchable<sObject>, Database.Stateful
{
    public List<string> errorMessages;

    public ClearStagingDataBatch() 
    {
    }

    public database.querylocator start( Database.BatchableContext bc ) 
    {
        errorMessages = new List<string>();

        string query = 
            'Select ' +
            '    Id, Project__c, Import_Status__c ' +
            'from ' +
            '    Staging_Project__c ' +
            'where ' +
            '    Project__c != null ';

        return Database.getQueryLocator( query );
    }

    public void execute( Database.BatchableContext bc, List<sObject> records )
    {
        try
        {
            Set<Id> projectIds = new Set<Id>();
            for( Staging_Project__c sp : (List<Staging_Project__c>)records )
            {
                if( sp.Project__c != null )
                {
                    projectIds.add( sp.Project__c );
                }
            }

            delete [SELECT ID FROM pse__Timecard_Header__c WHERE pse__Project__c in :projectIds];
            delete [SELECT ID FROM pse__Expense_Report__c WHERE pse__Project__c in :projectIds];
            delete [SELECT ID FROM pse__Milestone__c WHERE pse__Project__c in :projectIds];
            delete [SELECT ID FROM pse__Resource_Request__c WHERE pse__Project__c in :projectIds];
            delete [SELECT ID FROM pse__Assignment__c WHERE pse__Project__c in :projectIds];
            delete [SELECT ID FROM pse__Project_Task__c WHERE pse__Project__c in :projectIds];
            delete [SELECT ID FROM pse__Budget_Header__c WHERE pse__Project__c in :projectIds];
            delete [SELECT ID FROM pse__Budget_Allocation__c WHERE pse__Project__c in :projectIds];
            delete [SELECT ID FROM pse__Budget__c WHERE pse__Project__c in :projectIds];
            delete [SELECT ID FROM pse__Miscellaneous_Adjustment__c WHERE pse__Project__c in :projectIds];
            delete [SELECT ID FROM pse__Proj__c WHERE Id in :projectIds];

            delete [select id from role_budget__c where Project__c in :projectIds and external_id__c != null];
        }
        catch( Exception ex )
        {
            errorMessages.add( records[0].Id + ': ' + ex.getMessage() );
        }
    }

    public void finish( Database.BatchableContext BC ) 
    {
        if( this.errorMessages.size() > 0 )
        {
            AsyncApexJob batchJob = [Select Id, CreatedBy.Email from AsyncApexJob where Id =:BC.getJobId()];
            sendEmail( batchJob.CreatedBy.Email );
        }
    }

    public void sendEmail( string to ) 
    {
		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		mail.setToAddresses( new String[] {to} );

        string body = '<p>The data clear down process completed with errors</p>';

        mail.setSubject( 'The data clear down process has completed with errors!' );
        body += '<p>The following errors occurred:</p><ul>';
        for( String s : errorMessages ) 
        {
            body += '<li>' + s + '</li>';
        }
        body += '</ul>';

        /*Data_Import_Results__c res = new Data_Import_Results__c(
            Errors__c = body
        );
        insert res;*/

        body += '<p>User: ' + UserInfo.getUserName() + ', Org Id: ' + UserInfo.getOrganizationId() + '</p>';

		body += '<p>Certinia</p>';

		mail.setHtmlBody( body );

        try 
        {
		    Messaging.sendEmail( new Messaging.SingleEmailMessage[] { mail } );
        }
        catch( System.EmailException sex ) 
        {
        }
    }
}