unpackaged/main/default/objects/pse__Assignment__c/pse__Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Assignment__c/fields/Role_Budget__c.field-meta.xml
<CustomField>
    <fullName>Role_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Role Budget</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Role_Budget__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.pse__Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.pse__Role__c</field>
            <operation>equals</operation>
            <valueField>Role_Budget__c.Role__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Role_Budget__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task__c/pse__Project_Task__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Project_Task__c/fields/pse__Estimated_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Estimated_Hours__c</fullName>
    <label>Estimated Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task__c/fields/Role_Budget__c.field-meta.xml
<CustomField>
    <fullName>Role_Budget__c</fullName>
    <inlineHelpText>Role Budget Reference</inlineHelpText>
    <label>Role Budget Reference</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task_Assignment__c/pse__Project_Task_Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectTaskAssignmentHelp</customHelpPage>
    <description>Project task assignments are distinct from standard assignments. They associate a resource or resource role (for example, Project Manager) with a project task. Project tasks have a master-detail relationship with project task assignments.</description>
    <label>Project Task Assignment</label>
    <nameField>
        <displayFormat>PTA-{0}</displayFormat>
        <label>Project Task Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Project_Task_Assignment__c/fields/pse__Estimated_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Estimated_Hours__c</fullName>
    <description>The hours allocated to the resource on the project task assignment.</description>
    <inlineHelpText>The hours allocated to the resource on the project task assignment.</inlineHelpText>
    <label>Estimated Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task_Assignment__c/fields/pse__Project_Task__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Task__c</fullName>
    <description>Project Task to which the Resource is being Associated</description>
    <inlineHelpText>Project Task to which the Resource is being Associated</inlineHelpText>
    <label>Project Task</label>
    <referenceTo>pse__Project_Task__c</referenceTo>
    <relationshipLabel>Project Task Assignments</relationshipLabel>
    <relationshipName>Project_Task_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task_Assignment__c/fields/pse__Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource_Role__c</fullName>
    <label>Resource Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Solution Architect</fullName>
            </value>
            <value>
                <fullName>Team Lead</fullName>
            </value>
            <value>
                <fullName>Consultant (Finance)</fullName>
            </value>
            <value>
                <fullName>Consultant (HR)</fullName>
            </value>
            <value>
                <fullName>Consultant (Infrastructure)</fullName>
            </value>
            <value>
                <fullName>Consultant (Logistic Production)</fullName>
            </value>
            <value>
                <fullName>Consultant (Managed Services)</fullName>
            </value>
            <value>
                <fullName>Consultant (Principal)</fullName>
            </value>
            <value>
                <fullName>Customer Success Manager</fullName>
            </value>
            <value>
                <fullName>Database Engineer</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Project Coordinator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task_Assignment__c/fields/Role_Budget__c.field-meta.xml
<CustomField>
    <fullName>Role_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Populated by a flow. The Role budget linked to the PTA.</description>
    <label>Role Budget</label>
    <referenceTo>Role_Budget__c</referenceTo>
    <relationshipLabel>Project Task Assignments</relationshipLabel>
    <relationshipName>Project_Task_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Role_Budget__c/Role_Budget__c.object-meta.xml
<CustomObject>
    <label>Role Budget</label>
    <nameField>
        <displayFormat>RB-{00000}</displayFormat>
        <label>Role Budget</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Role_Budget__c/fields/Hours_Budget__c.field-meta.xml
<CustomField>
    <fullName>Hours_Budget__c</fullName>
    <label>Hours Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/RoleBudgetHelper.cls
public class RoleBudgetHelper 
{
    public static Set<Id> GetMaxedOutTasks( Set<Id> taskIds )
    {
        List<pse__Project_Task_Assignment__c> ptas = new List<pse__Project_Task_Assignment__c>();
        Set<Id> roleBudgetIds = new Set<Id>();

        for( pse__Project_Task_Assignment__c pta : 
            [Select 
                Id, 
                pse__Assignment__c,
                pse__Resource_Role__c,
                Role_Budget__c,
                pse__Project_Task__c
            from 
                pse__Project_Task_Assignment__c 
            where 
                pse__Project_Task__c in :taskIds] )
        {
            ptas.add( pta );

            if( pta.Role_Budget__c != null )
            {
                roleBudgetIds.add( pta.Role_Budget__c );
            }
        }

        Set<Id> maxedRoleBudgetIds = new Set<Id>();

        for( Role_Budget__c roleBudget : 
            [Select 
                Id,
                Hours_Budget__c,
                (Select Id, pse__Estimated_Hours__c from Project_Task_Assignments__r) 
            from 
                Role_Budget__c 
            where 
                Id in :roleBudgetIds] )
        {
            decimal totalEstimatedHours = 0.0;
            for( pse__Project_Task_Assignment__c pta : roleBudget.Project_Task_Assignments__r )
            {
                if( pta.pse__Estimated_Hours__c != null )
                {
                    totalEstimatedHours += pta.pse__Estimated_Hours__c;
                }
            }

            if( totalEstimatedHours > roleBudget.Hours_Budget__c )
            {
                maxedRoleBudgetIds.add( roleBudget.Id );
            }
        }

        Set<Id> maxedOutTaskIds = new Set<Id>();

        for( pse__Project_Task_Assignment__c pta : ptas )
        {
            if( maxedRoleBudgetIds.contains( pta.Role_Budget__c ) )
            {
                maxedOutTaskIds.add( pta.pse__Project_Task__c );
            }
        }

        return maxedOutTaskIds;
    }
}