unpackaged/main/default/objects/pse__Assignment__c/pse__Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Assignment__c/fields/Role_Budget__c.field-meta.xml
<CustomField>
    <fullName>Role_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Role Budget</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Role_Budget__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.pse__Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.pse__Role__c</field>
            <operation>equals</operation>
            <valueField>Role_Budget__c.Role__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Role_Budget__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task__c/pse__Project_Task__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Project_Task__c/fields/Role_Budget__c.field-meta.xml
<CustomField>
    <fullName>Role_Budget__c</fullName>
    <inlineHelpText>Role Budget Reference</inlineHelpText>
    <label>Role Budget Reference</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task__c/fields/Role_Budget_Link__c.field-meta.xml
<CustomField>
    <fullName>Role_Budget_Link__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Role Budget Link</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Role_Budget__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.pse__Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Role_Budget__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks_del</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task_Assignment__c/pse__Project_Task_Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectTaskAssignmentHelp</customHelpPage>
    <description>Project task assignments are distinct from standard assignments. They associate a resource or resource role (for example, Project Manager) with a project task. Project tasks have a master-detail relationship with project task assignments.</description>
    <label>Project Task Assignment</label>
    <nameField>
        <displayFormat>PTA-{0}</displayFormat>
        <label>Project Task Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Project_Task_Assignment__c/fields/pse__Project_Task__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Task__c</fullName>
    <description>Project Task to which the Resource is being Associated</description>
    <inlineHelpText>Project Task to which the Resource is being Associated</inlineHelpText>
    <label>Project Task</label>
    <referenceTo>pse__Project_Task__c</referenceTo>
    <relationshipLabel>Project Task Assignments</relationshipLabel>
    <relationshipName>Project_Task_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task_Assignment__c/fields/Role_Budget__c.field-meta.xml
<CustomField>
    <fullName>Role_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Populated by a flow. The Role budget linked to the PTA.</description>
    <label>Role Budget</label>
    <referenceTo>Role_Budget__c</referenceTo>
    <relationshipLabel>Project Task Assignments</relationshipLabel>
    <relationshipName>Project_Task_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Resource_Request__c/pse__Resource_Request__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ResourceRequestHelp</customHelpPage>
    <description>Operating as a means of asking for resources to staff an existing or planned project, resource requests collect information to help users responsible for staffing and assignment creation to choose the right resource. The user requesting the resource (e.g., project manager or sales professional) may create a resource request from an opportunity or project, or generate them based on project tasks and project task assignments. Held resource requests, or “soft bookings”, occur when a named resource has been reserved for a project or opportunity, but not yet assigned to the project.</description>
    <label>Resource Request</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Resource Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Resource_Request__c/fields/Role_Budget__c.field-meta.xml
<CustomField>
    <fullName>Role_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Role Budget</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Role_Budget__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.pse__Project__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.pse__Resource_Role__c</field>
            <operation>equals</operation>
            <valueField>Role_Budget__c.Role__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Role_Budget__c</referenceTo>
    <relationshipLabel>Resource Requests</relationshipLabel>
    <relationshipName>Resource_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Role_Budget__c/Role_Budget__c.object-meta.xml
<CustomObject>
    <label>Role Budget</label>
    <nameField>
        <displayFormat>RB-{00000}</displayFormat>
        <label>Role Budget</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ProjectTaskHelper.cls
public class ProjectTaskHelper 
{
    public static void TriggerHandler()
    {
        Map<Id,pse__Project_Task__c> changedProjectTasks = new Map<Id,pse__Project_Task__c>();

        if( trigger.isUpdate && trigger.isAfter )
        {
            for( pse__Project_Task__c task : (List<pse__Project_Task__c>)trigger.new )
            {
                pse__Project_Task__c old = (pse__Project_Task__c)trigger.oldMap.get( task.Id );
                if( task.Role_Budget_Link__c != null && old.Role_Budget_Link__c != null && 
                    task.Role_Budget_Link__c != old.Role_Budget_Link__c )
                {
                    // the role budget has changed
                    changedProjectTasks.put( task.Id, task );
                }
            }
        }

        if( changedProjectTasks.size() == 0 )
        {
            return;
        }

        Set<Id> assignmentIds = new Set<Id>();
        Map<Id,List<pse__Project_Task_Assignment__c>> taskToPTAs = new Map<Id,List<pse__Project_Task_Assignment__c>>();

        for( pse__Project_Task_Assignment__c pta : 
            [Select 
                Id,
                Role_Budget__c,
                pse__Project_Task__c,
                pse__Assignment__c,
                pse__Assignment__r.Role_Budget__c,
                pse__Resource_Request__c,
                pse__Resource_Request__r.Role_Budget__c
            from 
                pse__Project_Task_Assignment__c 
            where 
                pse__Project_Task__c in :changedProjectTasks.keySet()] )
        {
            if( pta.pse__Assignment__c != null )
            {
                assignmentIds.add( pta.pse__Assignment__c );
            }

            if( !taskToPTAs.containsKey( pta.pse__Project_Task__c ) )
            {
                taskToPTAs.put( pta.pse__Project_Task__c, new List<pse__Project_Task_Assignment__c>() );
            }
            taskToPTAs.get( pta.pse__Project_Task__c ).add( pta );
        }

        Map<Id,Set<Id>> assignmentToTasks = new Map<Id,Set<Id>>();
        Map<Id,pse__Assignment__c> assignments = new Map<Id,pse__Assignment__c>();
        for( pse__Assignment__c assignment : 
            [Select 
                Id,
                Role_Budget__c,
                (Select Id, Role_Budget__c, pse__Project_Task__c, pse__Project_Task__r.Role_Budget__c from pse__Project_Task_Assignments__r) 
            from 
                pse__Assignment__c 
            where 
                Id in :assignmentIds] )
        {
            Set<Id> taskIds = new Set<Id>();
            for( pse__Project_Task_Assignment__c pta : assignment.pse__Project_Task_Assignments__r )
            {
                if( pta.pse__Project_Task__c != null )
                {
                    taskIds.add( pta.pse__Project_Task__c );
                }
            }

            if( taskIds.size() > 0 )
            {
                assignmentToTasks.put( assignment.Id, taskIds );
            }

            assignments.put( assignment.Id, assignment );
        }

        Map<Id,pse__Project_Task_Assignment__c> changedPTAs = new Map<Id,pse__Project_Task_Assignment__c>();
        Map<Id,pse__Assignment__c> changedAssignments = new Map<Id,pse__Assignment__c>();
        Map<Id,pse__Resource_Request__c> changedResourceRequests = new Map<Id,pse__Resource_Request__c>();

        for( pse__Project_Task__c task : changedProjectTasks.values() )
        {
            Set<Id> taskAssignmentIds = new Set<Id>();
            if( taskToPTAs.containsKey( task.Id ) )
            {
                for( pse__Project_Task_Assignment__c pta : taskToPTAs.get( task.Id ) )
                {
                    Id assignmentId = pta.pse__Assignment__c;
                    if( assignmentId == null )
                    {
                        // easy, just change the PTA and resource request and we're done
                        pta.Role_Budget__c = task.Role_Budget_Link__c;
                        changedPTAs.put( pta.Id, pta );

                        system.debug( 'x: ' + pta.Id + ' ' + pta.pse__Resource_Request__c );

                        if( pta.pse__Resource_Request__c != null )
                        {
                            pta.pse__Resource_Request__r.Role_Budget__c = task.Role_Budget_Link__c;
                            changedResourceRequests.put( pta.pse__Resource_Request__c, pta.pse__Resource_Request__r );
                        }
                    }
                    else
                    {
                        taskAssignmentIds.add( assignmentId );
                    }
                }
            }

            if( taskAssignmentIds.size() > 0 )
            {
                for( Id assignmentId : taskAssignmentIds )
                {
                    Set<Id> taskIds = assignmentToTasks.get( assignmentId );
                    if( taskIds.contains( task.Id ) )
                    {
                        for( pse__Project_Task_Assignment__c pta : taskToPTAs.get( task.Id ) )
                        {
                            if( taskIds.size() > 1 )
                            {
                                // we have tasks other than this one associated with the assignment
                                pta.pse__Assignment__c = null;
                            }
                            pta.Role_Budget__c = task.Role_Budget_Link__c;
                            changedPTAs.put( pta.Id, pta );

                            system.debug( 'y: ' + pta.Id + ' ' + pta.pse__Resource_Request__c );

                            if( pta.pse__Resource_Request__c != null )
                            {
                                pta.pse__Resource_Request__r.Role_Budget__c = task.Role_Budget_Link__c;
                                changedResourceRequests.put( pta.pse__Resource_Request__c, pta.pse__Resource_Request__r );
                            }
                        }

                        if( taskIds.size() == 1 )
                        {
                            // we have a pure assignment so we can update it too
                            pse__Assignment__c assignment = assignments.get( assignmentId );
                            assignment.Role_Budget__c = task.Role_Budget_Link__c;
                            changedAssignments.put( assignment.Id, assignment );
                        }
                    }
                }
            }

            // update everything we've touched
            update changedPTAs.values();
            update changedAssignments.values();
            update changedResourceRequests.values();
        }
    }
}