unpackaged/main/default/objects/pse__Assignment__c/pse__Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Assignment__c/fields/pse__End_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__End_Date__c</fullName>
    <formula>pse__Schedule__r.pse__End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/pse__Assignment__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <formula>pse__Schedule__r.pse__Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task_Assignment__c/pse__Project_Task_Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectTaskAssignmentHelp</customHelpPage>
    <description>Project task assignments are distinct from standard assignments. They associate a resource or resource role (for example, Project Manager) with a project task. Project tasks have a master-detail relationship with project task assignments.</description>
    <label>Project Task Assignment</label>
    <nameField>
        <displayFormat>PTA-{0}</displayFormat>
        <label>Project Task Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Project_Task_Assignment__c/fields/pse__Estimated_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Estimated_Hours__c</fullName>
    <description>The hours allocated to the resource on the project task assignment.</description>
    <inlineHelpText>The hours allocated to the resource on the project task assignment.</inlineHelpText>
    <label>Estimated Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task_Assignment__c/fields/pse__Project_Task_End_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Task_End_Date__c</fullName>
    <formula>pse__Project_Task__r.pse__End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Task End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task_Assignment__c/fields/pse__Project_Task_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Task_Start_Date__c</fullName>
    <formula>pse__Project_Task__r.pse__Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Task Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/pse__Resource_Request__c/pse__Resource_Request__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ResourceRequestHelp</customHelpPage>
    <description>Operating as a means of asking for resources to staff an existing or planned project, resource requests collect information to help users responsible for staffing and assignment creation to choose the right resource. The user requesting the resource (e.g., project manager or sales professional) may create a resource request from an opportunity or project, or generate them based on project tasks and project task assignments. Held resource requests, or “soft bookings”, occur when a named resource has been reserved for a project or opportunity, but not yet assigned to the project.</description>
    <label>Resource Request</label>
    <nameField>
        <displayFormat>RR-{0000000}</displayFormat>
        <label>Resource Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Resource_Request__c/fields/pse__End_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/pse__Resource_Request__c/fields/pse__SOW_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__SOW_Hours__c</fullName>
    <inlineHelpText>Requested hours for this resource request.</inlineHelpText>
    <label>Requested Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Resource_Request__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/ProjectTaskAssignmentTriggerHandler.cls
public class ProjectTaskAssignmentTriggerHandler 
{
    public ProjectTaskAssignmentTriggerHandler() 
    {
    }

    public static void handleUpdate()
    {
        Set<Id> resourceRequestIds = new Set<Id>();

        for( pse__Project_Task_Assignment__c pta : (List<pse__Project_Task_Assignment__c>)trigger.new )
        {
            pse__Project_Task_Assignment__c old = (pse__Project_Task_Assignment__c)trigger.oldMap.get( pta.Id );

            if( pta.pse__Assignment__c == null && 
                pta.pse__Resource_Request__c != null &&
                (   pta.pse__Project_Task_Start_Date__c != old.pse__Project_Task_Start_Date__c ||
                    pta.pse__Project_Task_End_Date__c != old.pse__Project_Task_End_Date__c ||
                    pta.pse__Estimated_Hours__c != old.pse__Estimated_Hours__c ||
                    pta.pse__Allocation_Hours__c != old.pse__Allocation_Hours__c ) 
                )
            {
                resourceRequestIds.add( pta.pse__Resource_Request__c );
            }
        }

        if( trigger.isBefore || resourceRequestIds.size() == 0 )
        {
            return;
        }

        UpdateResourceRequestsFromPTAs( resourceRequestIds );
    }

    public static void UpdateResourceRequestsFromPTAs( Set<Id> resourceRequestIds )
    {
        List<pse__Resource_Request__c> resourceRequestsToUpdate = new List<pse__Resource_Request__c>();
        for( pse__Resource_Request__c rr : 
            [Select 
                Id,
                pse__SOW_Hours__c,
                pse__Start_Date__c,
                pse__End_Date__c,
                (Select 
                    Id,
                    pse__Estimated_Hours__c,
                    pse__Allocation_Hours__c,
                    pse__Project_Task_Start_Date__c,
                    pse__Project_Task_End_Date__c
                from 
                    pse__Project_Task_Assignments__r
                where
                    pse__Assignment__c = null)
            from 
                pse__Resource_Request__c 
            where 
                Id in :resourceRequestIds and
                pse__Resource_Held__c = false and
                pse__Preferred_Schedule__c = null and
                pse__Assignment__c = null] )
        {
            decimal totalHours = 0;
            date oldestStartDate = null;
            date newestEndDate = null;

            for( pse__Project_Task_Assignment__c pta : rr.pse__Project_Task_Assignments__r )
            {
                if( pta.pse__Allocation_Hours__c != null && pta.pse__Allocation_Hours__c > 0 )
                {
                    totalHours += pta.pse__Allocation_Hours__c;
                }
                else if( pta.pse__Estimated_Hours__c != null )
                {
                    totalHours += pta.pse__Estimated_Hours__c;
                }

                if( oldestStartDate == null || oldestStartDate > pta.pse__Project_Task_Start_Date__c )
                {
                    oldestStartDate = pta.pse__Project_Task_Start_Date__c;
                }
                if( newestEndDate == null || newestEndDate < pta.pse__Project_Task_End_Date__c )
                {
                    newestEndDate = pta.pse__Project_Task_End_Date__c;
                }
            }

            // some estimated hours appear to be of the .3333333 repeating variety
            totalHours = totalHours.setScale( 2 );

            if( rr.pse__SOW_Hours__c != totalHours || rr.pse__Start_Date__c != oldestStartDate || rr.pse__End_Date__c != newestEndDate )
            {
                rr.pse__SOW_Hours__c = totalHours;
                rr.pse__Start_Date__c = oldestStartDate;
                rr.pse__End_Date__c = newestEndDate;
                resourceRequestsToUpdate.add( rr );
            }
        }

        if( resourceRequestsToUpdate.size() > 0 )
        {
            update resourceRequestsToUpdate;
        }
    }
}