unpackaged/main/default/objects/pse__Assignment__c/pse__Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__AssignmentAndScheduleHelp</customHelpPage>
    <description>Stores information about the allocation of a resource to a project and specifies the bill rate and cost rate for time entered. It references the schedule for a resource and, optionally, a project milestone.</description>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Project_Task__c/pse__Project_Task__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Project_Task__c/fields/Number_of_Resource_Assignments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Resource_Assignments__c</fullName>
    <description>Rollup from DLRS</description>
    <label>Number of Resource Assignments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task_Assignment__c/pse__Project_Task_Assignment__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectTaskAssignmentHelp</customHelpPage>
    <description>Project task assignments are distinct from standard assignments. They associate a resource or resource role (for example, Project Manager) with a project task. Project tasks have a master-detail relationship with project task assignments.</description>
    <label>Project Task Assignment</label>
    <nameField>
        <displayFormat>PTA-{0}</displayFormat>
        <label>Project Task Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Project_Task_Assignment__c/fields/pse__Project_Task__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Task__c</fullName>
    <description>Project Task to which the Resource is being Associated</description>
    <inlineHelpText>Project Task to which the Resource is being Associated</inlineHelpText>
    <label>Project Task</label>
    <referenceTo>pse__Project_Task__c</referenceTo>
    <relationshipLabel>Project Task Assignments</relationshipLabel>
    <relationshipName>Project_Task_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/AssignmentTriggerHandler.cls
public class AssignmentTriggerHandler 
{
    public AssignmentTriggerHandler() 
    {
    }

    private static Set<Id> ptIdsToRecalculate = new Set<Id>();

    public static void handleDelete()
    {
        if( trigger.isBefore )
        {
            ptIdsToRecalculate = new Set<Id>();
            
            // figure out the project tasks to recalculate before the links are deleted
            Set<Id> assignmentIds = new Set<Id>();
            for( pse__Assignment__c assignment : (List<pse__Assignment__c>)trigger.old )
            {
                assignmentIds.add( assignment.Id );
            }

            for( pse__Project_Task_Assignment__c pta : 
                [Select 
                    Id, 
                    pse__Project_Task__c 
                from 
                    pse__Project_Task_Assignment__c 
                where 
                    pse__Assignment__c in :assignmentIds] )
            {
                ptIdsToRecalculate.add( pta.pse__Project_Task__c );
            }
        }
        else
        {
            // now do the actual recalculation of the project tasks
            List<pse__Project_Task__c> ptsToUpdate = new List<pse__Project_Task__c>();
            for( pse__Project_Task__c pt : 
                [Select 
                    Id,
                    Number_of_Resource_Assignments__c,
                    (Select Id from pse__Project_Task_Assignments__r where pse__Assignment__c != null)
                from 
                    pse__Project_Task__c 
                where 
                    Id in :ptIdsToRecalculate] )
            {
                integer assignments = pt.pse__Project_Task_Assignments__r.size();
                if( pt.Number_of_Resource_Assignments__c != assignments )
                {
                    pt.Number_of_Resource_Assignments__c = assignments;
                    ptsToUpdate.add( pt );
                }
            }

            if( ptsToUpdate.size() > 0 )
            {
                update ptsToUpdate;
            }
        }
    }
}