unpackaged/main/default/objects/Contact/fields/Clarizen_ID__c.field-meta.xml
<CustomField>
    <fullName>Clarizen_ID__c</fullName>
    <description>Used for Data Migration and Plan D ERP Integration.</description>
    <label>Clarizen ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Deleted_Task_Time_Split__c/Deleted_Task_Time_Split__c.object-meta.xml
<CustomObject>
    <label>Deleted Task Time Split</label>
    <nameField>
        <displayFormat>DTTS{000000}</displayFormat>
        <label>Deleted Task Time Split Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deleted Task Time Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Deleted_Task_Time_Split__c/fields/Revoke_Reason__c.field-meta.xml
<CustomField>
    <fullName>Revoke_Reason__c</fullName>
    <label>Revoke Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Deleted_Task_Time_Split__c/fields/Revoke_State__c.field-meta.xml
<CustomField>
    <fullName>Revoke_State__c</fullName>
    <label>Revoke State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Granted</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Deleted_Task_Time_Split__c/fields/Revoked_By__c.field-meta.xml
<CustomField>
    <fullName>Revoked_By__c</fullName>
    <label>Revoked By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Deleted_Task_Time_Split__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Deleted_Task_Time_Split__c/fields/Task_Time_Split_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Time_Split_Id__c</fullName>
    <externalId>true</externalId>
    <label>Task Time Split Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Deleted_Task_Time_Split__c/fields/Timecard__c.field-meta.xml
<CustomField>
    <fullName>Timecard__c</fullName>
    <label>Timecard</label>
    <referenceTo>pse__Timecard_Header__c</referenceTo>
    <relationshipLabel>Deleted Task Time Splits</relationshipLabel>
    <relationshipName>Deleted_Task_Time_Splits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard__c/pse__Timecard__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__TimecardSplitHelp</customHelpPage>
    <description>Represents a whole timecard or part of a timecard. PSA creates timecard splits when a timecard spans the boundary of a time period, allowing you to bill for part of a timecard. Submission, approval, and inclusion in financials occur on the timecard, but subsequent billing and invoicing are associated with child timecard splits. Note the object name, Timecard, and API name, pse__Timecard__c. Timecards (pse__Timecard_Header__c) have a master-detail relationship with timecard splits.</description>
    <label>Timecard Split</label>
    <nameField>
        <displayFormat>TC-{MM}-{DD}-{YYYY}-{000000}</displayFormat>
        <label>Timecard Split Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecard Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Timecard__c/fields/pse__Timecard_Header__c.field-meta.xml
<CustomField>
    <fullName>pse__Timecard_Header__c</fullName>
    <label>Timecard Header</label>
    <referenceTo>pse__Timecard_Header__c</referenceTo>
    <relationshipLabel>Timecard Splits</relationshipLabel>
    <relationshipName>TimecardSplits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/pse__Timecard_Header__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__TimecardHelp</customHelpPage>
    <description>Records the hours and days worked by a resource in a given week. Timecards are associated with a project and may also be logged against an assignment or milestone, or against one or more project tasks. Resources can submit multiple timecards on the Timecard Entry page, accessed by clicking either “Log a Timecard - New UI” or “Log a Timecard with Task Time” on the PSA Links sidebar (depending on whether your organization logs time against project tasks). This object is named Timecard_Header (API name pse__Timecard_Header__c) and has a master-detail relationship with timecard splits.</description>
    <label>Timecard</label>
    <nameField>
        <displayFormat>TCH-{MM}-{DD}-{YYYY}-{000000}</displayFormat>
        <label>Timecard Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Distance_Friday__c.field-meta.xml
<CustomField>
    <fullName>Distance_Friday__c</fullName>
    <label>Distance - Friday</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Distance_Monday__c.field-meta.xml
<CustomField>
    <fullName>Distance_Monday__c</fullName>
    <label>Distance - Monday</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Distance_Saturday__c.field-meta.xml
<CustomField>
    <fullName>Distance_Saturday__c</fullName>
    <label>Distance - Saturday</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Distance_Sunday__c.field-meta.xml
<CustomField>
    <fullName>Distance_Sunday__c</fullName>
    <label>Distance - Sunday</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Distance_Thursday__c.field-meta.xml
<CustomField>
    <fullName>Distance_Thursday__c</fullName>
    <label>Distance - Thursday</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Distance_Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Distance_Tuesday__c</fullName>
    <label>Distance - Tuesday</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Distance_Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Distance_Wednesday__c</fullName>
    <label>Distance - Wednesday</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Per_Diem_Friday__c.field-meta.xml
<CustomField>
    <fullName>Per_Diem_Friday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Per Diem - Friday</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Per_Diem_Monday__c.field-meta.xml
<CustomField>
    <fullName>Per_Diem_Monday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Per Diem - Monday</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Per_Diem_Saturday__c.field-meta.xml
<CustomField>
    <fullName>Per_Diem_Saturday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Per Diem - Saturday</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Per_Diem_Sunday__c.field-meta.xml
<CustomField>
    <fullName>Per_Diem_Sunday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Per Diem - Sunday</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Per_Diem_Thursday__c.field-meta.xml
<CustomField>
    <fullName>Per_Diem_Thursday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Per Diem - Thursday</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Per_Diem_Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Per_Diem_Tuesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Per Diem - Tuesday</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Per_Diem_Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Per_Diem_Wednesday__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Per Diem - Wednesday</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/pse__Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.pse__Is_Resource__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.pse__Is_Resource_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/pse__Status__c.field-meta.xml
<CustomField>
    <fullName>pse__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Revoke_Reason__c.field-meta.xml
<CustomField>
    <fullName>Revoke_Reason__c</fullName>
    <description>Used by Plan D Integration.</description>
    <label>Revoke Reason</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Revoked__c.field-meta.xml
<CustomField>
    <fullName>Revoked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by Plan D integration.</description>
    <label>Revoked</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/pse__Timecard_Header__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <description>Used by ERP Integration (Plan D).</description>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Extracted</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Failed Sync</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Pending Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/Task_Time_Split__c.object-meta.xml
<CustomObject>
    <description>Splits task times down to a per-day basis</description>
    <label>Task Time Split</label>
    <nameField>
        <displayFormat>TaskTimeSplit-{000000}</displayFormat>
        <label>Task Time Split Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Time Splits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Task_Time_Split__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <label>Days</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <label>Hours</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Extracted</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Failed Sync</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Pending Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/fields/Task_Time__c.field-meta.xml
<CustomField>
    <fullName>Task_Time__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Time</label>
    <referenceTo>pse__Task_Time__c</referenceTo>
    <relationshipLabel>Task Time Splits</relationshipLabel>
    <relationshipName>Task_Time_Splits</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split_Settings__c/Task_Time_Split_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Task Time Split Settings</label>
</CustomObject>

unpackaged/main/default/objects/Task_Time_Split_Settings__c/fields/Enable_Task_Time_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Enable_Task_Time_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Task Time Trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split_Settings__c/fields/Enable_Timecard_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Enable_Timecard_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Timecard Trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/TaskTimeHelper.cls
public class TaskTimeHelper 
{
    public class AppException extends Exception {}

    public static void TimecardHeaderTriggerHandler()
    {
        if( !Task_Time_Split_Settings__c.getInstance().Enable_Timecard_Trigger__c )
        {
            return;
        }

        // we can't create a master detail on task time split so have to handle the fact that a 
        // delete here won't cascade and fire the task time delete trigger
        Set<Id> timecardIds = new Set<Id>();
        Set<Id> approvedIds = new Set<Id>();
        for( pse__Timecard_Header__c tc : (List<pse__Timecard_Header__c>)trigger.old )
        {
            timecardIds.add( tc.Id );

            if( trigger.isUpdate )
            {
                if( ((pse__Timecard_Header__c)trigger.newMap.get( tc.Id )).pse__Status__c == 'Approved' )
                {
                    approvedIds.add( tc.Id );
                }
            }
        }

        if( trigger.isDelete )
        {
            List<Task_Time_Split__c> splitsToDelete = new List<Task_Time_Split__c>();
            Set<string> syncedStatuses = new Set<string>{ 'Extracted', 'Synced', 'Invoiced', 'Pending Invoice' };

            for( Task_Time_Split__c split : [Select Id, Task_Time__r.pse__Timecard__c, Sync_Status__c from Task_Time_Split__c where Task_Time__r.pse__Timecard__c in :timecardIds] )
            {
                if( syncedStatuses.contains( split.Sync_Status__c ) )
                {
                    trigger.oldMap.get( split.Task_Time__r.pse__Timecard__c ).addError( 'This timecard cannot be deleted as it has a task time split that has been synced externally' );
                }
                else
                {
                    splitsToDelete.add( split );
                }
            }

            if( splitsToDelete.size() > 0 )
            {
                delete splitsToDelete;
            }
        }

        if( trigger.isUpdate )
        {
            PushDistanceFromTimecardToTaskTimeSplits( approvedIds );
        }
    }

    public static void HandleTimesheetRevocation( Id timecardId, string reason )
    {
        // get the timecard
        List<pse__Timecard_Header__c> timecards = 
            [Select 
                Id,
                pse__Approved__c,
                pse__Status__c,
                pse__Include_In_Financials__c,
                pse__Submitted__c,
                pse__Resource__c,
                pse__Resource__r.Clarizen_ID__c,
                pse__Resource__r.Email,
                Revoked__c,
                Revoke_Reason__c
            from 
                pse__Timecard_Header__c 
            where 
                Id = :timecardId];

        if( timecards.size() == 0 )
        {
            throw new AppException( 'Unable to find the timecard with id ' + timecardId );
        }

        if( string.isBlank( reason ) )
        {
            throw new AppException( 'You must provide a revocation reason' );
        }

        pse__Timecard_Header__c timecard = timecards[0];

        if( timecard.pse__Approved__c != true )
        {
            throw new AppException( 'You can only revoke approved timecards' );
        }

        string revokedBy = timecard.pse__Resource__r.Email;
        if( !string.isBlank( timecard.pse__Resource__r.Clarizen_ID__c ) )
        {
            revokedBy = timecard.pse__Resource__r.Clarizen_ID__c;
        }

        // gather the splits to delete
        List<Task_Time_Split__c> splitsToDelete = new List<Task_Time_Split__c>();
        List<Task_Time_Split__c> syncedSplits = new List<Task_Time_Split__c>();
        Set<string> syncedStatuses = new Set<string>{ 'Extracted', 'Synced', 'Pending Invoice' };
        List<Deleted_Task_Time_Split__c> deletedTaskTimeSplits = new List<Deleted_Task_Time_Split__c>();
        Set<Id> effectedTaskTimeIds = new Set<Id>();

        for( Task_Time_Split__c split : [Select Id, Task_Time__c, Sync_Status__c from Task_Time_Split__c where Task_Time__r.pse__Timecard__c = :timecardId] )
        {
            // if any are invoiced we fail the whole process
            if( split.Sync_Status__c == 'Invoiced' )
            {
                throw new AppException( 'Some of the time has been invoiced so this timecard cannot be revoked' );
            }

            if( syncedStatuses.contains( split.Sync_Status__c ) )
            {
                syncedSplits.add( split );
                effectedTaskTimeIds.add( split.Task_Time__c );

                deletedTaskTimeSplits.add( new Deleted_Task_Time_Split__c(
                    Timecard__c = timecardId,
                    Task_Time_Split_Id__c = split.Id,
                    Sync_Status__c = 'New',
                    Revoke_State__c = 'Requested',
                    Revoke_Reason__c = reason,
                    Revoked_By__c = revokedBy
                ) );
            }
            splitsToDelete.add( split );
        }

        if( syncedSplits.size() > 0 )
        {
            // record the deleted splits, then actually delete them
            insert deletedTaskTimeSplits;
            delete splitsToDelete;

            // now trigger recreation of new timecard splits
            List<pse__Task_Time__c> taskTimes = new List<pse__Task_Time__c>();
            for( Id taskTimeId : effectedTaskTimeIds )
            {
                taskTimes.add( new pse__Task_Time__c( Id = taskTimeId  ) );
            }
            update taskTimes;
        }

        // un-approve the timecard
        timecard.pse__Approved__c = false;
        timecard.pse__Status__c = 'Saved';
        timecard.pse__Include_In_Financials__c = false;
        timecard.pse__Submitted__c = false;
        timecard.Revoked__c = true;
        timecard.Revoke_Reason__c = reason;

        update timecard;
    }

    public static void TriggerHandler()
    {
        // check custom setting to disable functionality
        if( !Task_Time_Split_Settings__c.getInstance().Enable_Task_Time_Trigger__c )
        {
            return;
        }

        // get the task time ids
        Set<Id> taskTimeIds = new Set<Id>();
        if( trigger.isDelete )
        {
            taskTimeIds = trigger.oldMap.keySet();
        }
        else if( trigger.isInsert || trigger.isUpdate )
        {
            taskTimeIds = trigger.newMap.keySet();
        }

        Set<Id> timecardIds = new Set<Id>();

        // get all task time splits for effected task times
        Map<Id,List<Task_Time_Split__c>> taskTimeToSplits = new Map<Id,List<Task_Time_Split__c>>();
        for( Task_Time_Split__c split : 
            [Select 
                Id, 
                Days__c, 
                Hours__c, 
                Notes__c, 
                Start_Date__c, 
                Sync_Status__c, 
                Task_Time__c,
                Task_Time__r.pse__Timecard__c 
            from 
                Task_Time_Split__c 
            where 
                Task_Time__c in :taskTimeIds] )
        {
            if( !taskTimeToSplits.containsKey( split.Task_Time__c ) )
            {
                taskTimeToSplits.put( split.Task_Time__c, new List<Task_Time_Split__c>() );
            }
            taskTimeToSplits.get( split.Task_Time__c ).add( split );
        }

        // deletion / update - prevent deletion if any task time splits are synced
        if( trigger.isDelete || trigger.isUpdate )
        {
            List<sObject> splitsToDelete = new List<sObject>();
            Set<string> syncedStatuses = new Set<string>{ 'Extracted', 'Synced', 'Invoiced', 'Pending Invoice' };

            for( sObject taskTime : trigger.old )
            {
                boolean failed = false;
                if( taskTimeToSplits.containsKey( taskTime.Id ) )
                {
                    for( Task_Time_Split__c split : taskTimeToSplits.get( taskTime.Id ) )
                    {
                        if( syncedStatuses.contains( split.Sync_Status__c ) )
                        {
                            taskTime.addError( 'This task time cannot be modified as it has been synced externally' );
                            failed = true;
                        }
                    }
                }

                if( !failed && trigger.isDelete )
                {
                    // no problems, so we can delete the child splits
                    splitsToDelete.addAll( taskTimeToSplits.get( taskTime.Id ) );
                }
            }

            if( splitsToDelete.size() > 0 )
            {
                for( Task_Time_Split__c split : (List<Task_Time_Split__c>)splitsToDelete )
                {
                    if( split.Task_Time__c != null && split.Task_Time__r.pse__Timecard__c != null )
                    {
                        timecardIds.add( split.Task_Time__r.pse__Timecard__c );
                    }
                }

                delete splitsToDelete;
            }
        }

        // insert - split down the task time into days
        if( trigger.isInsert )
        {
            List<Task_Time_Split__c> splits = new List<Task_Time_Split__c>();
            for( pse__Task_Time__c taskTime : (List<pse__Task_Time__c>)trigger.new )
            {
                Date dt = taskTime.pse__Start_Date__c;

                if( taskTime.pse__Timecard__c != null )
                {
                    timecardIds.add( taskTime.pse__Timecard__c );
                }

                for( Integer i = 0; i < 7; i++ )
                {
                    string dayOfWeek = dayOfWeek( dt );

                    Task_Time_Split__c split = new Task_Time_Split__c(
                        Task_Time__c = taskTime.Id,
                        CurrencyIsoCode = taskTime.CurrencyIsoCode,
                        Start_Date__c = dt,
                        Days__c = (decimal)taskTime.get( 'pse__' + dayOfWeek + '_Days__c'),
                        Hours__c = (decimal)taskTime.get( 'pse__' + dayOfWeek + '_Hours__c'),
                        Notes__c = (string)taskTime.get( 'pse__' + dayOfWeek + '_Notes__c'),
                        Sync_Status__c = 'New'                        
                    );

                    // only create splits that actually have values
                    //if( getVal( split.Days__c ) != 0.0 || getVal( split.Hours__c ) != 0.0 )
                    {
                        splits.add( split );
                    }

                    dt = dt.addDays( 1 );
                }
            }

            insert splits;
        }

        // update - make sure at the end we have splits that match the task time
        if( trigger.isUpdate )
        {
            List<Task_Time_Split__c> splits = new List<Task_Time_Split__c>();
            List<Task_Time_Split__c> splitsToDelete = new List<Task_Time_Split__c>();

            for( pse__Task_Time__c taskTime : (List<pse__Task_Time__c>)trigger.new )
            {
                if( taskTime.getErrors().size() > 0 )
                {
                    // if we've marked one of the task times as invalid, skip processing it here
                    continue;
                }

                if( taskTime.pse__Timecard__c != null )
                {
                    timecardIds.add( taskTime.pse__Timecard__c );
                }

                Date dt = taskTime.pse__Start_Date__c;

                for( Integer i = 0; i < 7; i++ )
                {
                    string dayOfWeek = dayOfWeek( dt );
                    Task_Time_Split__c splitForDay;
                    if( taskTimeToSplits.containsKey( taskTime.Id ) )
                    {
                        for( Task_Time_Split__c split : taskTimeToSplits.get( taskTime.Id ) )
                        {
                            if( split.Start_Date__c == dt )
                            {
                                splitForDay = split;
                                break;
                            }
                        }
                    }

                    if( splitForDay == null )
                    {
                        Task_Time_Split__c split = new Task_Time_Split__c(
                            Task_Time__c = taskTime.Id,
                            CurrencyIsoCode = taskTime.CurrencyIsoCode,
                            Start_Date__c = dt,
                            Days__c = (decimal)taskTime.get( 'pse__' + dayOfWeek + '_Days__c'),
                            Hours__c = (decimal)taskTime.get( 'pse__' + dayOfWeek + '_Hours__c'),
                            Notes__c = (string)taskTime.get( 'pse__' + dayOfWeek + '_Notes__c'),
                            Sync_Status__c = 'New'                        
                        );

                        //if( getVal( split.Days__c ) != 0.0 || getVal( split.Hours__c ) != 0.0 )
                        {
                            splits.add( split );
                        }
                    }
                    else
                    {
                        splitForDay.Days__c = (decimal)taskTime.get( 'pse__' + dayOfWeek + '_Days__c');
                        splitForDay.Hours__c = (decimal)taskTime.get( 'pse__' + dayOfWeek + '_Hours__c');
                        splitForDay.Notes__c = (string)taskTime.get( 'pse__' + dayOfWeek + '_Notes__c');

                        //if( getVal( splitForDay.Days__c ) != 0.0 || getVal( splitForDay.Hours__c ) != 0.0 )
                        {
                            splits.add( splitForDay );
                        }
                        /*else
                        {
                            // the split no longer has a value so is up for deletion
                            splitsToDelete.add( splitForDay );
                        }*/
                    }

                    dt = dt.addDays( 1 );
                }
            }

            upsert splits;

            if( splitsToDelete.size() > 0 )
            {
                delete splitsToDelete;
            }

            PushDistanceFromTimecardToTaskTimeSplits( timecardIds );
        }
    }

    public static void PushDistanceFromTimecardToTaskTimeSplits( Set<Id> timecardIds )
    {
        List<Task_Time_Split__c> splitsToUpdate = new List<Task_Time_Split__c>();

        Map<Id,pse__Timecard_Header__c> timecards = new Map<Id,pse__Timecard_Header__c>();
        Map<Id,List<pse__Task_Time__c>> timecardToTaskTimes = new Map<Id,List<pse__Task_Time__c>>();

        for( pse__Task_Time__c taskTime : 
            [Select 
                Id,
                pse__Start_Date__c,
                pse__Timecard__c,
                pse__Timecard__r.Distance_Monday__c,
                pse__Timecard__r.Distance_Tuesday__c,
                pse__Timecard__r.Distance_Wednesday__c,
                pse__Timecard__r.Distance_Thursday__c,
                pse__Timecard__r.Distance_Friday__c,
                pse__Timecard__r.Distance_Saturday__c,
                pse__Timecard__r.Distance_Sunday__c,
                pse__Timecard__r.Per_Diem_Monday__c,
                pse__Timecard__r.Per_Diem_Tuesday__c,
                pse__Timecard__r.Per_Diem_Wednesday__c,
                pse__Timecard__r.Per_Diem_Thursday__c,
                pse__Timecard__r.Per_Diem_Friday__c,
                pse__Timecard__r.Per_Diem_Saturday__c,
                pse__Timecard__r.Per_Diem_Sunday__c,
                (Select Id, Start_Date__c, Distance__c, Per_Diem__c from Task_Time_Splits__r) 
            from 
                pse__Task_Time__c
            where
                pse__Timecard__c in :timecardIds
            order by 
                pse__Timecard__c, createddate] )
        {
            if( !timecards.containsKey( taskTime.pse__Timecard__c ) )
            {
                timecards.put( taskTime.pse__Timecard__c, taskTime.pse__Timecard__r );
                timecardToTaskTimes.put( taskTime.pse__Timecard__c, new List<pse__Task_Time__c>() );
            }

            timecardToTaskTimes.get( taskTime.pse__Timecard__c ).add( taskTime );
        }

        for( pse__Timecard_Header__c timecard : timecards.values() )
        {
            // we only want to push the distance and per diem down to a single task time (splits)
            boolean firstTaskTime = true;
            for( pse__Task_Time__c taskTime : timecardToTaskTimes.get( timecard.Id ) )
            {
                for( Task_Time_Split__c split : taskTime.Task_Time_Splits__r )
                {
                    Date dt = split.Start_Date__c;
                    string dayOfWeek = dayOfWeek( dt );

                    if( firstTaskTime )
                    {
                        split.Distance__c = (decimal)timecard.get( 'Distance_' + dayOfWeek + '__c' );
                        split.Per_Diem__c = (boolean)timecard.get( 'Per_Diem_' + dayOfWeek + '__c' );
                    }
                    else
                    {
                        split.Distance__c = 0;
                        split.Per_Diem__c = false;
                    }

                    splitsToUpdate.add( split );
                }

                firstTaskTime = false;
            }
        }     
        
        if( splitsToUpdate.size() > 0 )
        {
            update splitsToUpdate;
        }
    }

    public static decimal getVal( decimal val )
    {
        return val == null ? 0.0 : val;
    }

    public static string dayOfWeek( Date theDate )
    {
        Integer day = Math.mod( Date.newInstance( 1900, 1, 7 ).daysBetween( theDate ), 7 );

        switch on day
        {
            when 0
            {
                return 'Sunday';
            }
            when 1
            {
                return 'Monday';
            }
            when 2
            {
                return 'Tuesday';
            }
            when 3
            {
                return 'Wednesday';
            }
            when 4
            {
                return 'Thursday';
            }
            when 5
            {
                return 'Friday';
            }
            when 6
            {
                return 'Saturday';
            }
            when else
            {
                throw new AppException( 'Unexpected day' );
            }
        }
    }
}