unpackaged/main/default/objects/Contact/fields/Clarizen_ID__c.field-meta.xml
<CustomField>
    <fullName>Clarizen_ID__c</fullName>
    <description>Used for Data Migration and Plan D ERP Integration.</description>
    <label>Clarizen ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Proj__c/fields/Customer_Contact_Reference__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact_Reference__c</fullName>
    <description>Free text field to record the customer contact for invoices and contact.</description>
    <label>Customer Contact Reference</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>ErrorMessage</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/External_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Project_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Project Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/Invoice_Contact_Reference__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Contact_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Poopulated manually or by flow.</description>
    <label>Invoice Contact Reference</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.pse__Is_Resource_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Invoice Contact Reference)</relationshipLabel>
    <relationshipName>Projects2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/Lead_Consultant__c.field-meta.xml
<CustomField>
    <fullName>Lead_Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Consultant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Lead Consultant)</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <description>Used for Integration and Data Migration.</description>
    <label>Order Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/Project_Sub_Types__c.field-meta.xml
<CustomField>
    <fullName>Project_Sub_Types__c</fullName>
    <label>Project Sub-Types</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>pse__Project_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSS - Implementation</fullName>
            </value>
            <value>
                <fullName>NSS - Reference Implementation</fullName>
            </value>
            <value>
                <fullName>IBS - Upgrade</fullName>
            </value>
            <value>
                <fullName>IBS - Enhancement</fullName>
            </value>
            <value>
                <fullName>IBS - Ongoing Work</fullName>
            </value>
            <value>
                <fullName>IBS - Cloud Migration</fullName>
            </value>
            <value>
                <fullName>IBS - Subscription Managed Services</fullName>
            </value>
            <value>
                <fullName>PS Subscription - Managed Services</fullName>
            </value>
            <value>
                <fullName>PS Subscription - Forterro Service Points</fullName>
            </value>
            <value>
                <fullName>PS Subscription - Customisation Maintenance</fullName>
            </value>
            <value>
                <fullName>Internal - Business Development</fullName>
            </value>
            <value>
                <fullName>Internal - Packaged Solutions</fullName>
            </value>
            <value>
                <fullName>Internal - Field Innovation</fullName>
            </value>
            <value>
                <fullName>Internal - Organisational Development</fullName>
            </value>
            <value>
                <fullName>Internal - Administration</fullName>
            </value>
            <value>
                <fullName>Internal – Cross-Functional Work</fullName>
            </value>
            <value>
                <fullName>Internal – Unavailability</fullName>
            </value>
            <value>
                <fullName>IBS – Upgrade</fullName>
                <isActive>false</isActive>
                <label>IBS – Upgrade</label>
            </value>
            <value>
                <fullName>Internal - Cross-Functional Work</fullName>
                <isActive>false</isActive>
                <label>Internal - Cross-Functional Work</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Account__c.field-meta.xml
<CustomField>
    <fullName>pse__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>pse__Billing_Type__c</fullName>
    <label>Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Price</fullName>
            </value>
            <value>
                <fullName>Time and Materials</fullName>
            </value>
            <value>
                <fullName>Mixed</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__End_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if this project is billable to a customer.</inlineHelpText>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person responsible for this project (optional). If not provided, it's assumed that the record Owner is the project manager.</description>
    <label>Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.pse__Is_Resource__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.pse__Is_Resource_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects Managed</relationshipLabel>
    <relationshipName>ProjectsManaged</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Project_Type__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Type__c</fullName>
    <description>A descriptive classification of the project</description>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>NSS</fullName>
            </value>
            <value>
                <fullName>IBS</fullName>
            </value>
            <value>
                <fullName>PS Subscription</fullName>
            </value>
            <value>
                <fullName>Packaged Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Stage__c.field-meta.xml
<CustomField>
    <fullName>pse__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pse__Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Extracted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Failed Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/SyncDate__c.field-meta.xml
<CustomField>
    <fullName>SyncDate__c</fullName>
    <label>SyncDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/pse__Region__c/pse__Region__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__RegionHelp</customHelpPage>
    <description>An entity that represents a geographic area in which you do business. Regions are organized as an independent hierarchy determined by the Parent Region field, with parent and child records of the same type. Every region in the hierarchy may contain projects, resources (contacts), and other objects. The hierarchy allows roll-ups of revenue, cost, and time totals.</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Region__c/fields/BU_Code__c.field-meta.xml
<CustomField>
    <fullName>BU_Code__c</fullName>
    <description>Used in Integration with ERP.</description>
    <label>BU Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ProjectAPI.cls
@RestResource(urlMapping='/projectsapi/projects/*')
global with sharing class ProjectAPI 
{
    public class AppException extends Exception {}

    private final static String BASE_URI = '/projectsapi/projects/';
    private final static integer MAX_RECORDS = 1000;

    global class Project
    {
        public string projectId;
        public string externalProjectId;
        public string projectName;
        public string projectOwner;
        public string projectOwnerName;
        public string customerID;
        public string customerName;
        public string businessUnit;
        public string buCode;
        public string projectType;
        public string projectSubType;
        public string projectBillingType;
        public string projectStatus;
        public Date startDate;
        public Date endDate;
        public string recordType;
        public DateTime syncDate;
        public string syncState;
        public string errorMessage;
        public boolean isBillable;
        public string currencyISOcode;
        public string invoiceContactReference;
        public string customerContact;
        public string orderId;

        global Project()
        {
        }

        public Project( pse__Proj__c project )
        {
            projectId = project.pse__Project_ID__c;
            externalProjectId = RestAPIHelper.sanitiseProjectId( project.External_Project_Id__c );
            projectName = project.Name;
            if( project.pse__Project_Manager__c != null )
            {
                projectOwnerName = project.pse__Project_Manager__r.Name;
                projectOwner = string.isblank( project.pse__Project_Manager__r.Clarizen_ID__c ) ? 
                    project.pse__Project_Manager__r.Email : 
                    project.pse__Project_Manager__r.Clarizen_ID__c;
            }
            else if( project.Lead_Consultant__c != null )
            {
                projectOwnerName = project.Lead_Consultant__r.Name;
                projectOwner = string.isblank( project.Lead_Consultant__r.Clarizen_ID__c ) ? 
                    project.Lead_Consultant__r.Email : 
                    project.Lead_Consultant__r.Clarizen_ID__c;
            }
            if( project.Invoice_Contact_Reference__c != null )
            {
                invoiceContactReference = project.Invoice_Contact_Reference__r.Name;
            }
            customerID = project.pse__Account__r.AccountNumber;
            customerName = project.pse__Account__r.Name;
            if( project.pse__Region__c != null )
            {
                businessUnit = project.pse__Region__r.Name;
                buCode = project.pse__Region__r.BU_Code__c;
            }
            projectType = project.pse__Project_Type__c;
            projectSubType = project.Project_Sub_Types__c;
            projectBillingType = project.pse__Billing_Type__c;
            projectStatus = project.pse__Stage__c;
            startDate = project.pse__Start_Date__c;
            endDate = project.pse__End_Date__c;
            recordType = project.RecordTypeId == null ? '' : project.RecordType.Name;
            syncDate = project.SyncDate__c;
            syncState = project.Sync_Status__c;
            errorMessage = project.ErrorMessage__c;
            isBillable = project.pse__Is_Billable__c;
            currencyISOcode = project.CurrencyIsoCode;
            customerContact = project.Customer_Contact_Reference__c;
            orderId = project.Order_Id__c;
        }
    }

    global class ProjectUpdate
    {
        public string projectId;
        public string errorMessage;
        public string syncState;
        public DateTime syncDate;
    }

    @HttpGet
    global static void HandleGet()
    {
        Savepoint savePoint = Database.setSavepoint();

        try
        {
            RestRequest req = RestContext.request;
            string context = req.requestURI.substring( req.requestURI.indexOf(BASE_URI) + BASE_URI.length() );

            List<pse__Region__c> regions = [Select Id from pse__Region__c where BU_Code__c = :context];
            if( regions.size() == 0 )
            {
                throw new AppException( 'Failed to find business unit code ' + context );
            }

            List<Project> projects = new List<Project>();
            List<string> allowedSyncStates = new List<string>{ 'New', 'Pending' };

            for( pse__Proj__c soProject :
                [Select
                    Id,
                    pse__Project_ID__c,
                    External_Project_Id__c,
                    Name,
                    CurrencyIsoCode,
                    pse__Project_Manager__c,
                    pse__Project_Manager__r.Clarizen_ID__c,
                    pse__Project_Manager__r.Name,
                    pse__Project_Manager__r.Email,
                    Lead_Consultant__c,
                    Lead_Consultant__r.Clarizen_ID__c,
                    Lead_Consultant__r.Name,
                    Lead_Consultant__r.Email,
                    Invoice_Contact_Reference__c,
                    Invoice_Contact_Reference__r.Name,
                    pse__Account__c,
                    pse__Account__r.AccountNumber,
                    pse__Account__r.Name,
                    pse__Region__c,
                    pse__Region__r.Name,
                    pse__Region__r.BU_Code__c,
                    pse__Project_Type__c,
                    Project_Sub_Types__c,
                    pse__Billing_Type__c,
                    pse__Stage__c,
                    pse__Start_Date__c,
                    pse__End_Date__c,
                    RecordTypeId,
                    RecordType.Name,
                    SyncDate__c,
                    Sync_Status__c,
                    ErrorMessage__c,
                    pse__Is_Billable__c,
                    Customer_Contact_Reference__c,
                    Order_Id__c
                From
                    pse__Proj__c
                Where
                    Sync_Status__c in :allowedSyncStates and
                    pse__Stage__c != 'Requested' and
                    pse__Stage__c != 'Draft' and
                    pse__Stage__c != null and
                    pse__Is_Billable__c = true and
                    pse__Account__r.AccountNumber != '' and
                    pse__Region__r.BU_Code__c = :context
                Limit
                    :MAX_RECORDS] )
            {
                Project proj = new Project( soProject );
                projects.add( proj );
            }

            RestAPIHelper.SetRestReturn( projects, false );
        }
        catch( Exception ex )
        {
            RestAPIHelper.SetRestError( 400, 'BAD_REQUEST', new List<string>{ ex.getMessage() } );
            Database.rollback( savePoint );
        }
    }

    @HttpPost
    global static void HandlePost( ProjectUpdate[] projectUpdates )
    {
        Savepoint savePoint = Database.setSavepoint();

        try
        {
            Map<string,ProjectUpdate> projectUpdateMap = new Map<string,ProjectUpdate>();
            for( ProjectUpdate projectUpdate : projectUpdates )
            {
                projectUpdateMap.put( projectUpdate.projectId, projectUpdate );
            }

            Map<string,pse__Proj__c> projects = new Map<string,pse__Proj__c>();
            for( pse__Proj__c project : 
                [Select 
                    Id, 
                    pse__Project_ID__c, 
                    Sync_Status__c, 
                    ErrorMessage__c, 
                    SyncDate__c 
                from 
                    pse__Proj__c 
                where 
                    pse__Project_ID__c in :projectUpdateMap.keySet()] )
            {
                projects.put( project.pse__Project_ID__c, project );
            }

            List<pse__Proj__c> projectsToUpdate = new List<pse__Proj__c>();
            List<string> errors = new List<string>();

            for( ProjectUpdate projectUpdate : projectUpdates )
            {
                if( !projects.containsKey( projectUpdate.projectId ) )
                {
                    errors.add( 'Project ' + projectUpdate.projectId + ' not found' );
                    continue;
                }

                pse__Proj__c project = projects.get( projectUpdate.projectId );
                project.Sync_Status__c = projectUpdate.syncState;
                project.ErrorMessage__c = projectUpdate.errorMessage;

                if( projectUpdate.syncDate != null )
                {
                    project.SyncDate__c = projectUpdate.syncDate;
                }

                if( projectUpdate.syncState == 'Synced' && project.SyncDate__c == null )
                {
                    project.SyncDate__c = system.now();
                }

                projectsToUpdate.add( project );
            }

            if( errors.size() > 0 )
            {
                RestAPIHelper.SetRestError( 400, 'BAD_REQUEST', errors );
            }
            else
            {
                update projectsToUpdate;
                RestAPIHelper.SetRestReturn( projectUpdateMap.size(), true );
            }
        }
        catch( Exception ex )
        {
            RestAPIHelper.SetRestError( 400, 'BAD_REQUEST', new List<string>{ ex.getMessage() } );
            Database.rollback( savePoint );
        }
    }
}