unpackaged/main/default/objects/Contact/fields/pse__Is_Resource__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Resource__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resource</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/pse__Is_Resource_Active__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Resource_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Resource Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/pse__Resource_Role__c.field-meta.xml
<CustomField>
    <fullName>pse__Resource_Role__c</fullName>
    <label>Resource Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Consultant (Finance)</fullName>
            </value>
            <value>
                <fullName>Consultant (HR)</fullName>
            </value>
            <value>
                <fullName>Consultant (Infrastructure)</fullName>
            </value>
            <value>
                <fullName>Consultant (Logistic Production)</fullName>
            </value>
            <value>
                <fullName>Consultant (Managed Services)</fullName>
            </value>
            <value>
                <fullName>Consultant (Principal)</fullName>
            </value>
            <value>
                <fullName>Customer Success Manager</fullName>
            </value>
            <value>
                <fullName>Database Engineer</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Project Coordinator</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Solution Architect</fullName>
            </value>
            <value>
                <fullName>Team Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Account__c.field-meta.xml
<CustomField>
    <fullName>pse__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Billing_Type__c.field-meta.xml
<CustomField>
    <fullName>pse__Billing_Type__c</fullName>
    <label>Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Price</fullName>
            </value>
            <value>
                <fullName>Time and Materials</fullName>
            </value>
            <value>
                <fullName>Mixed</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if this project is billable to a customer.</inlineHelpText>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Work_Calendar__c.field-meta.xml
<CustomField>
    <fullName>pse__Work_Calendar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Calendar</label>
    <referenceTo>pse__Work_Calendar__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Project_Work_Calendar</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Work_Calendar__c/pse__Work_Calendar__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__WorkCalendarHelp</customHelpPage>
    <description>Defines the standard working days, regular hours, and public holidays for a resource, region, practice or group.</description>
    <label>Work Calendar</label>
    <nameField>
        <label>Work Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Calendars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Work_Calendar__c/fields/pse__Friday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Friday_Hours__c</fullName>
    <defaultValue>8</defaultValue>
    <inlineHelpText>Enter the number of hours regularly worked on this day. For example, enter 8 for an eight hour day.</inlineHelpText>
    <label>Friday Hours</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Work_Calendar__c/fields/pse__Monday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Monday_Hours__c</fullName>
    <defaultValue>8</defaultValue>
    <inlineHelpText>Enter the number of hours regularly worked on this day. For example, enter 8 for an eight hour day.</inlineHelpText>
    <label>Monday Hours</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Work_Calendar__c/fields/pse__Saturday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Saturday_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Enter the number of hours regularly worked on this day. For example, enter 8 for an eight hour day.</inlineHelpText>
    <label>Saturday Hours</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Work_Calendar__c/fields/pse__Sunday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Sunday_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Enter the number of hours regularly worked on this day. For example, enter 8 for an eight hour day.</inlineHelpText>
    <label>Sunday Hours</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Work_Calendar__c/fields/pse__Thursday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Thursday_Hours__c</fullName>
    <defaultValue>8</defaultValue>
    <inlineHelpText>Enter the number of hours regularly worked on this day. For example, enter 8 for an eight hour day.</inlineHelpText>
    <label>Thursday Hours</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Work_Calendar__c/fields/pse__Tuesday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Tuesday_Hours__c</fullName>
    <defaultValue>8</defaultValue>
    <inlineHelpText>Enter the number of hours regularly worked on this day. For example, enter 8 for an eight hour day.</inlineHelpText>
    <label>Tuesday Hours</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Work_Calendar__c/fields/pse__Wednesday_Hours__c.field-meta.xml
<CustomField>
    <fullName>pse__Wednesday_Hours__c</fullName>
    <defaultValue>8</defaultValue>
    <inlineHelpText>Enter the number of hours regularly worked on this day. For example, enter 8 for an eight hour day.</inlineHelpText>
    <label>Wednesday Hours</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/pse__Work_Calendar__c/fields/pse__Week_Start_Day__c.field-meta.xml
<CustomField>
    <fullName>pse__Week_Start_Day__c</fullName>
    <inlineHelpText>Select the day of the week your region's calendar starts on.</inlineHelpText>
    <label>Week Start Day</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
                <default>true</default>
                <label>Sunday</label>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Role_Budget__c/Role_Budget__c.object-meta.xml
<CustomObject>
    <label>Role Budget</label>
    <nameField>
        <displayFormat>RB-{00000}</displayFormat>
        <label>Role Budget</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Role Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Role_Budget__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Bill Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Role_Budget__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Consultant (Finance)</fullName>
            </value>
            <value>
                <fullName>Consultant (HR)</fullName>
            </value>
            <value>
                <fullName>Consultant (Infrastructure)</fullName>
            </value>
            <value>
                <fullName>Consultant (Logistic Production)</fullName>
            </value>
            <value>
                <fullName>Consultant (Managed Services)</fullName>
            </value>
            <value>
                <fullName>Consultant (Principal)</fullName>
            </value>
            <value>
                <fullName>Customer Success Manager</fullName>
            </value>
            <value>
                <fullName>Database Engineer</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Project Coordinator</fullName>
            </value>
            <value>
                <fullName>Solution Architect</fullName>
            </value>
            <value>
                <fullName>Team Lead</fullName>
            </value>
            <value>
                <fullName>Consultant (Business Process Functional)</fullName>
                <isActive>false</isActive>
                <label>Consultant (Business Process Functional)</label>
            </value>
            <value>
                <fullName>Consultant Developer (App Development &amp; Integrations)</fullName>
                <isActive>false</isActive>
                <label>Consultant Developer (App Development &amp; Integrations)</label>
            </value>
            <value>
                <fullName>Consultant Developer IBS (App Development &amp; Integrations)</fullName>
                <isActive>false</isActive>
                <label>Consultant Developer IBS (App Development &amp; Integrations)</label>
            </value>
            <value>
                <fullName>Consultant Developer NSS (App Development &amp; Integrations)</fullName>
                <isActive>false</isActive>
                <label>Consultant Developer NSS (App Development &amp; Integrations)</label>
            </value>
            <value>
                <fullName>Consultant IBS (Business Process Functional)</fullName>
                <isActive>false</isActive>
                <label>Consultant IBS (Business Process Functional)</label>
            </value>
            <value>
                <fullName>Consultant NSS (Business Process Functional)</fullName>
                <isActive>false</isActive>
                <label>Consultant NSS (Business Process Functional)</label>
            </value>
            <value>
                <fullName>Custom Development</fullName>
                <isActive>false</isActive>
                <label>Custom Development</label>
            </value>
            <value>
                <fullName>Customer Success</fullName>
                <isActive>false</isActive>
                <label>Customer Success</label>
            </value>
            <value>
                <fullName>Developer (Cust)</fullName>
                <isActive>false</isActive>
                <label>Developer (Cust)</label>
            </value>
            <value>
                <fullName>Developer (PS)</fullName>
                <isActive>false</isActive>
                <label>Developer (PS)</label>
            </value>
            <value>
                <fullName>External (Sub Consulting)</fullName>
                <isActive>false</isActive>
                <label>External (Sub Consulting)</label>
            </value>
            <value>
                <fullName>Infrastructure Consultant</fullName>
                <isActive>false</isActive>
                <label>Infrastructure Consultant</label>
            </value>
            <value>
                <fullName>Infrastructure Consultant - Accounts</fullName>
                <isActive>false</isActive>
                <label>Infrastructure Consultant - Accounts</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/GetExtProjectForRegionTest.cls
@isTest
public class GetExtProjectForRegionTest 
{
    @TestSetup
    static void makeData()
    {
        pse__Region__c region1 = new pse__Region__c(
            Name = 'Region1'
        );
        insert region1;

        pse__Region__c region2 = new pse__Region__c(
            Name = 'Region2',
            pse__Parent_Region__c = region1.Id
        );
        insert region2;

        pse__Region__c region3 = new pse__Region__c(
            Name = 'Region3',
            pse__Parent_Region__c = region2.Id
        );
        insert region3;

        pse__Work_Calendar__c cal = new pse__Work_Calendar__c(
            Name ='Test Calender',
            pse__Week_Start_Day__c = 'Sunday',
            pse__Sunday_Hours__c = 0.0,
            pse__Monday_Hours__c = 8.0,
            pse__Tuesday_Hours__c = 8.0,
            pse__Wednesday_Hours__c = 8.0,
            pse__Thursday_Hours__c = 8.0,
            pse__Friday_Hours__c = 8.0,
            pse__Saturday_Hours__c = 0.0
        );
        insert cal;

        Account acc = new Account(
            Name = 'Test account',
            AccountNumber = '123456'
        );
        insert acc;

        Contact res = new Contact(
            AccountId = acc.Id,
            FirstName = 'Test',
            LastName = 'Resource',
            pse__Region__c = region2.Id,
            CurrencyIsoCode = 'EUR',
            pse__Is_Resource_Active__c = true,
            pse__Is_Resource__c = true,
            pse__Resource_Role__c = 'Consultant',
            pse__Default_Cost_Rate__c = 80.0,
            pse__Work_Calendar__c = cal.Id,
            pse__Salesforce_User__c = UserInfo.getUserId()
        );
        insert res;

        pse__Proj__c project = new pse__Proj__c(
            Name = 'Test (EXT) project',
            pse__Account__c = acc.Id,
            pse__Billing_Type__c = 'Time and Materials',
            pse__Is_Billable__c = true,
            pse__Region__c = region1.Id,
            pse__Is_Active__c = true,
            pse__Allow_Timecards_Without_Assignment__c = true,
            pse__Allow_Expenses_Without_Assignment__c = true,
            pse__Project_Manager__c = res.Id,
            Sync_Status__c = 'New',
            pse__Project_Type__c = 'IBS',
            Project_Sub_Types__c = 'IBS - Enhancement'
        );
        insert project;

        Role_Budget__c roleBudget = new Role_Budget__c(
            Project__c = project.Id,
            Hours_Budget__c = 100,
            Rate__c = 50,
            Role__c = 'Consultant'
        );
        insert roleBudget;

        project.pse__Stage__c = 'In Progress';
        update project;
    }

    @isTest static void TestMultipleRegionLevels()
    {
        GetExtProjectForRegion.InputParameters input = new GetExtProjectForRegion.InputParameters();
        input.regionId = [Select Id from pse__Region__c where Name = 'Region3'].Id;

        List<GetExtProjectForRegion.OutputParameters> outputs = GetExtProjectForRegion.getProjectForRegion( 
            new List<GetExtProjectForRegion.InputParameters>{ input }
        );

        system.assert( outputs.size() == 1 );
        system.assert( outputs[0].projectIds.size() == 1 );
        system.assert( outputs[0].projectIds[0] == [Select Id from pse__Proj__c].Id );
    }

    @isTest static void TestSameRegionLevel()
    {
        GetExtProjectForRegion.InputParameters input = new GetExtProjectForRegion.InputParameters();
        input.regionId = [Select Id from pse__Region__c where Name = 'Region1'].Id;

        List<GetExtProjectForRegion.OutputParameters> outputs = GetExtProjectForRegion.getProjectForRegion( 
            new List<GetExtProjectForRegion.InputParameters>{ input }
        );

        system.assert( outputs.size() == 1 );
        system.assert( outputs[0].projectIds.size() == 1 );
        system.assert( outputs[0].projectIds[0] == [Select Id from pse__Proj__c].Id );
    }
}