unpackaged/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Proj__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Lead Customer Contact for the Project</description>
    <inlineHelpText>Lookup to Lead Customer Contact for the Project</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Contact)</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>ErrorMessage</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/External_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Project_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Project Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <description>Used for Integration and Data Migration.</description>
    <label>Order Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Account__c.field-meta.xml
<CustomField>
    <fullName>pse__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Group__c.field-meta.xml
<CustomField>
    <fullName>pse__Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group</label>
    <referenceTo>pse__Grp__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Practice__c.field-meta.xml
<CustomField>
    <fullName>pse__Practice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practice</label>
    <referenceTo>pse__Practice__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person responsible for this project (optional). If not provided, it's assumed that the record Owner is the project manager.</description>
    <label>Project Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.pse__Is_Resource__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.pse__Is_Resource_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only active resources are shown. To display all resources, click Show all results.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects Managed</relationshipLabel>
    <relationshipName>ProjectsManaged</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Extracted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Failed Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/SyncDate__c.field-meta.xml
<CustomField>
    <fullName>SyncDate__c</fullName>
    <label>SyncDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task__c/pse__Project_Task__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectTaskHelp</customHelpPage>
    <description>Represents a unit or collection of work associated with a project, often tracked for completion with points and for effort with hours. You can associate one or more resources or roles with a project task through corresponding child project task assignments. If configured, resources can enter the number of hours that they have spent on a particular task on the Timecard Entry page, accessed from the Log a Timecard with Task Time link or button. Resources can log Timecards against one or multiple tasks.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Project_Task__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <description>Order ID from ERP. Used by Integration.</description>
    <label>Order Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task__c/fields/pse__Description__c.field-meta.xml
<CustomField>
    <fullName>pse__Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task__c/fields/pse__Project__c.field-meta.xml
<CustomField>
    <fullName>pse__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Project that the Task is a part of.</description>
    <inlineHelpText>You do not have to define the Project field when creating a child task. The Project field auto-populates from the parent task and overwrites any entered value.</inlineHelpText>
    <label>Project</label>
    <referenceTo>pse__Proj__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Project_Task__c/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <label>Task Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Contingent</fullName>
            </value>
            <value>
                <fullName>Product Bug</fullName>
            </value>
            <value>
                <fullName>Billable</fullName>
                <isActive>false</isActive>
                <label>Billable</label>
            </value>
            <value>
                <fullName>Free of Charge</fullName>
                <isActive>false</isActive>
                <label>Free of Charge</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/pse__Region__c/pse__Region__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__RegionHelp</customHelpPage>
    <description>An entity that represents a geographic area in which you do business. Regions are organized as an independent hierarchy determined by the Parent Region field, with parent and child records of the same type. Every region in the hierarchy may contain projects, resources (contacts), and other objects. The hierarchy allows roll-ups of revenue, cost, and time totals.</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Region__c/fields/BU_Code__c.field-meta.xml
<CustomField>
    <fullName>BU_Code__c</fullName>
    <description>Used in Integration with ERP.</description>
    <label>BU Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/pse__Task_Time__c/pse__Task_Time__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__TaskTimeHelp</customHelpPage>
    <description>Records time entered against project tasks on the Time Entry page and associates project tasks with timecards.</description>
    <label>Task Time</label>
    <nameField>
        <displayFormat>TaskTime-{000000}</displayFormat>
        <label>Task Time Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Time</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Task_Time__c/fields/pse__Project_Task__c.field-meta.xml
<CustomField>
    <fullName>pse__Project_Task__c</fullName>
    <label>Project Task</label>
    <referenceTo>pse__Project_Task__c</referenceTo>
    <relationshipLabel>Task Time</relationshipLabel>
    <relationshipName>Task_Time</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/pse__Timecard__c/pse__Timecard__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__TimecardSplitHelp</customHelpPage>
    <description>Represents a whole timecard or part of a timecard. PSA creates timecard splits when a timecard spans the boundary of a time period, allowing you to bill for part of a timecard. Submission, approval, and inclusion in financials occur on the timecard, but subsequent billing and invoicing are associated with child timecard splits. Note the object name, Timecard, and API name, pse__Timecard__c. Timecards (pse__Timecard_Header__c) have a master-detail relationship with timecard splits.</description>
    <label>Timecard Split</label>
    <nameField>
        <displayFormat>TC-{MM}-{DD}-{YYYY}-{000000}</displayFormat>
        <label>Timecard Split Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecard Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Timecard__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(pse__Timecard_Header__r.Type__c)</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/Task_Time_Split__c.object-meta.xml
<CustomObject>
    <description>Splits task times down to a per-day basis</description>
    <label>Task Time Split</label>
    <nameField>
        <displayFormat>TaskTimeSplit-{000000}</displayFormat>
        <label>Task Time Split Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Time Splits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Task_Time_Split__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <label>Distance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>ERP Error Message.</description>
    <label>ErrorMessage</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <label>Hours</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <description>Populated by ERP Integration</description>
    <label>Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <formula>Task_Time__r.pse__Project_Task__r.Order_Id__c</formula>
    <label>Order Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/fields/Per_Diem__c.field-meta.xml
<CustomField>
    <fullName>Per_Diem__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Per Diem</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Extracted</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Failed Sync</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Pending Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/fields/SyncDate__c.field-meta.xml
<CustomField>
    <fullName>SyncDate__c</fullName>
    <description>Date and Time of the ERP SYNC.</description>
    <label>SyncDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/fields/Task_Time__c.field-meta.xml
<CustomField>
    <fullName>Task_Time__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Time</label>
    <referenceTo>pse__Task_Time__c</referenceTo>
    <relationshipLabel>Task Time Splits</relationshipLabel>
    <relationshipName>Task_Time_Splits</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(Task_Time__r.pse__Timecard__r.Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TaskTimeAPI.cls
@RestResource(urlMapping='/tasktimeapi/tasktimes/*')
global with sharing class TaskTimeAPI 
{
    public class AppException extends Exception {}

    private final static String BASE_URI = '/tasktimeapi/tasktimes/';
    private final static integer MAX_RECORDS = 1000;
    private final static Set<string> NO_MILEAGE_ONLY_BUS = new Set<string>{ 'BPSC' };

    global class TimeEntry
    {
        public Id timeEntryId;
        public string reportedBy;
        public Date reportedDate;
        public decimal reportedHours;
        public string notes;
        public boolean isBillable;
        public decimal billedAmount;
        public string billingCurrency;
        public decimal billRate;
        public string timeType;
        public string businessUnitId;
        public string projectId;
        public string projectName;
        public string customerID;
        public string customerName;
        public string invoiceNumber;
        public string projectOwner;
        public string taskDescription;
        public string taskId;
        public string taskName;
        public boolean perDiemOnSite;
        public decimal distance;
        public string errorMessage;
        public DateTime syncDate;
        public string syncState;
        public DateTime approvedDate;
        public string taskType;
        public string orderID;
        public string resourcePractice;
        public string resourceRegion;
        public string resourceGroup;
        public string customerContact;
        public string projectType;
        public string projectSubType;
        public string taskStatus;
        public string projectStatus;
        public string roleBudget;
        public boolean location;
        public string fortXID;
        public string reportedByBUID;

        global TimeEntry()
        {
        }

        public TimeEntry( Task_Time_Split__c split )
        {
            timeEntryId = split.Id;
            reportedBy = split.Task_Time__r.pse__Timecard__r.pse__Resource__r.External_Id__c == null ?
                (string)split.Task_Time__r.pse__Timecard__r.pse__Resource__r.Email : split.Task_Time__r.pse__Timecard__r.pse__Resource__r.External_Id__c;
            reportedDate = split.Start_Date__c;
            reportedHours = split.Hours__c;
            notes = split.Notes__c;
            isBillable = split.Task_Time__r.pse__Timecard__r.pse__Billable__c;
            billedAmount = split.Hours__c * RestAPIHelper.zeroIfNull( split.Task_Time__r.pse__Timecard__r.pse__Bill_Rate__c );
            billingCurrency = split.Task_Time__r.pse__Timecard__r.CurrencyIsoCode;
            billRate = split.Task_Time__r.pse__Timecard__r.pse__Bill_Rate__c;
            timeType = split.Task_Time__r.pse__Timecard__r.Type__c;
            businessUnitId = split.Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Region__r.BU_Code__c;
            projectId = split.Task_Time__r.pse__Timecard__r.pse__Project__r.External_Project_Id__c == null ?
                (string)split.Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Project_ID__c : split.Task_Time__r.pse__Timecard__r.pse__Project__r.External_Project_Id__c;
            projectName = split.Task_Time__r.pse__Timecard__r.pse__Project__r.Name;
            customerID = split.Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Account__r.External_Id__c == null ?
                (string)split.Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Account__c : split.Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Account__r.External_Id__c;
            customerName = split.Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Account__r.Name;
            invoiceNumber = split.Invoice_Number__c;
            if( split.Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Project_Manager__c != null )
            {
                projectOwner = split.Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Project_Manager__r.Name;
            }
            taskDescription = split.Task_Time__r.pse__Project_Task__r.pse__Description__c;
            taskId = split.Task_Time__r.pse__Project_Task__r.pse__External_Task_ID__c == null ?
                (string)split.Task_Time__r.pse__Project_Task__c : split.Task_Time__r.pse__Project_Task__r.pse__External_Task_ID__c;
            taskName = split.Task_Time__r.pse__Project_Task__r.Name;
            perDiemOnSite = split.Per_Diem__c;
            distance = split.Distance__c;
            errorMessage = split.ErrorMessage__c;
            syncDate = split.SyncDate__c;
            syncState = split.Sync_Status__c;

            approvedDate = split.Task_Time__r.pse__Timecard__r.Approved_Date__c;
            taskType = split.Task_Time__r.pse__Project_Task__r.Task_Type__c;
            orderID = split.Task_Time__r.pse__Project_Task__r.Order_ID__c;
            resourcePractice = split.Task_Time__r.pse__Timecard__r.pse__Resource__r.pse__Practice__c == null ?
                '' : split.Task_Time__r.pse__Timecard__r.pse__Resource__r.pse__Practice__r.Name;
            resourceRegion = split.Task_Time__r.pse__Timecard__r.pse__Resource__r.pse__Region__c == null ?
                '' : split.Task_Time__r.pse__Timecard__r.pse__Resource__r.pse__Region__r.Name;
            resourceGroup = split.Task_Time__r.pse__Timecard__r.pse__Resource__r.pse__Group__c == null ?
                '' : split.Task_Time__r.pse__Timecard__r.pse__Resource__r.pse__Group__r.Name;
            customerContact = split.Task_Time__r.pse__Timecard__r.pse__Project__r.Contact__c == null ?
                '' : split.Task_Time__r.pse__Timecard__r.pse__Project__r.Contact__r.Name;
            projectType = split.Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Project_Type__c;
            projectSubType = split.Task_Time__r.pse__Timecard__r.pse__Project__r.Project_Sub_Types__c;
            taskStatus = split.Task_Time__r.pse__Project_Task__r.pse__Status__c;
            projectStatus = split.Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Stage__c;
            roleBudget = split.Task_Time__r.pse__Timecard__r.pse__Assignment__r?.Role_Budget__r?.Role_Budget_Name__c;
            location = split.Task_Time__r.pse__Timecard__r.Location__c == 'On-site' ? true : false;
            fortXID = split.Task_Time__r.pse__Timecard__r.pse__Resource__r.FortX_ID__c;
            reportedByBUID = split.Task_Time__r.pse__Timecard__r.pse__Resource__r.pse__Region__c == null ? '' : split.Task_Time__r.pse__Timecard__r.pse__Resource__r.pse__Region__r.BU_Code__c;
        }
    }

    global class TimeEntryUpdate
    {
        public Id timeEntryId;
        public string errorMessage;
        public string invoiceNumber;
        public DateTime syncDate;
        public string syncState;
    }

    @HttpPost
    global static void HandlePost( TimeEntryUpdate[] timeEntries )
    {
        Savepoint savePoint = Database.setSavepoint();

        try
        {
            Map<Id,TimeEntryUpdate> timeEntryMap = new Map<Id,TimeEntryUpdate>();
            for( TimeEntryUpdate entry : timeEntries )
            {
                timeEntryMap.put( entry.timeEntryId, entry );
            }

            Map<Id,Task_Time_Split__c> splits = new Map<Id,Task_Time_Split__c>(
                [Select Id, Sync_Status__c, ErrorMessage__c, SyncDate__c, Invoice_Number__c from Task_Time_Split__c where id in :timeEntryMap.keySet()]
            );

            List<Task_Time_Split__c> splitsToUpdate = new List<Task_Time_Split__c>();
            List<string> errors = new List<string>();

            for( TimeEntryUpdate entry : timeEntries )
            {
                if( !splits.containsKey( entry.timeEntryId ) )
                {
                    errors.add( 'Entry ' + entry.timeEntryId + ' not found' );
                    continue;
                }

                Task_Time_Split__c split = splits.get( entry.timeEntryId );
                split.Sync_Status__c = entry.syncState;
                split.ErrorMessage__c = entry.errorMessage;
                split.Invoice_Number__c = entry.invoiceNumber;

                if( entry.syncDate != null )
                {
                    split.SyncDate__c = entry.syncDate;
                }

                if( entry.syncState == 'Synced' && split.SyncDate__c == null )
                {
                    split.SyncDate__c = system.now();
                }

                splitsToUpdate.add( split );
            }

            if( errors.size() > 0 )
            {
                RestAPIHelper.SetRestError( 400, 'BAD_REQUEST', errors );
            }
            else
            {
                update splitsToUpdate;
                RestAPIHelper.SetRestReturn( timeEntryMap.size(), true );
            }
        }
        catch( Exception ex )
        {
            RestAPIHelper.SetRestError( 400, 'BAD_REQUEST', new List<string>{ ex.getMessage() } );
            Database.rollback( savePoint );
        }
    }

    @HttpGet
    global static void HandleGet()
    {
        Savepoint savePoint = Database.setSavepoint();

        try
        {
            RestRequest req = RestContext.request;
            string context = req.requestURI.substring( req.requestURI.indexOf(BASE_URI) + BASE_URI.length() );

            List<pse__Region__c> regions = [Select Id from pse__Region__c where BU_Code__c = :context];
            if( regions.size() == 0 )
            {
                throw new AppException( 'Failed to find business unit code ' + context );
            }

            List<TimeEntry> timeEntries = new List<TimeEntry>();

            for( Task_Time_Split__c split :
                [Select
                    Id, 
                    Start_Date__c, 
                    Days__c,
                    Hours__c,
                    Notes__c,
                    Distance__c, 
                    Per_Diem__c,
                    Invoice_Number__c,
                    Sync_Status__c,
                    SyncDate__c,
                    ErrorMessage__c,
                    Task_Time__c,
                    Task_Time__r.pse__Timecard__c,
                    Task_Time__r.pse__Timecard__r.Type__c,
                    Task_Time__r.pse__Timecard__r.CurrencyIsoCode,
                    Task_Time__r.pse__Timecard__r.pse__Billable__c,
                    Task_Time__r.pse__Timecard__r.pse__Bill_Rate__c,
                    Task_Time__r.pse__Timecard__r.Approved_Date__c,
                    Task_Time__r.pse__Timecard__r.Location__c,
                    Task_Time__r.pse__Timecard__r.pse__Resource__c,
                    Task_Time__r.pse__Timecard__r.pse__Resource__r.External_Id__c,
                    Task_Time__r.pse__Timecard__r.pse__Resource__r.Email,
                    Task_Time__r.pse__Timecard__r.pse__Resource__r.pse__Practice__c,
                    Task_Time__r.pse__Timecard__r.pse__Resource__r.pse__Practice__r.Name,
                    Task_Time__r.pse__Timecard__r.pse__Resource__r.pse__Region__c,
                    Task_Time__r.pse__Timecard__r.pse__Resource__r.pse__Region__r.Name,
                    Task_Time__r.pse__Timecard__r.pse__Resource__r.pse__Region__r.BU_Code__c,
                    Task_Time__r.pse__Timecard__r.pse__Resource__r.pse__Group__c,
                    Task_Time__r.pse__Timecard__r.pse__Resource__r.pse__Group__r.Name,
                    Task_Time__r.pse__Timecard__r.pse__Resource__r.FortX_ID__c,
                    Task_Time__r.pse__Timecard__r.pse__Project__c,
                    Task_Time__r.pse__Timecard__r.pse__Project__r.Name,
                    Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Region__c,
                    Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Region__r.BU_Code__c,
                    Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Project_ID__c,
                    Task_Time__r.pse__Timecard__r.pse__Project__r.External_Project_Id__c,
                    Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Project_Type__c,
                    Task_Time__r.pse__Timecard__r.pse__Project__r.Project_Sub_Types__c,
                    Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Account__c,
                    Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Account__r.Name,
                    Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Account__r.External_Id__c,
                    Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Project_Manager__c,
                    Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Project_Manager__r.Name,
                    Task_Time__r.pse__Timecard__r.pse__Project__r.Contact__c,
                    Task_Time__r.pse__Timecard__r.pse__Project__r.Contact__r.Name,
                    Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Stage__c,
                    Task_Time__r.pse__Timecard__r.pse__Assignment__r.Role_Budget__r.Role_Budget_Name__c,
                    Task_Time__r.pse__Project_Task__c,
                    Task_Time__r.pse__Project_Task__r.Name,
                    Task_Time__r.pse__Project_Task__r.pse__Description__c,
                    Task_Time__r.pse__Project_Task__r.pse__External_Task_ID__c,
                    Task_Time__r.pse__Project_Task__r.Task_Type__c,
                    Task_Time__r.pse__Project_Task__r.pse__Status__c,
                    Task_Time__r.pse__Project_Task__r.Order_ID__c
                From
                    Task_Time_Split__c
                Where
                    Sync_Status__c = 'New' and
                    Task_Time__r.pse__Timecard__r.pse__Status__c = 'Approved' and
                    Task_Time__r.pse__Timecard__r.pse__Approved__c = true and
                    Task_Time__r.pse__Timecard__r.pse__Include_In_Financials__c = true and
                    Task_Time__r.pse__Timecard__r.pse__Submitted__c = true and
                    Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Region__r.BU_Code__c = :context and
                    ( 
                        Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Region__r.BU_Code__c not in :NO_MILEAGE_ONLY_BUS or 
                        ( Hours__c > 0.0 ) 
                    ) and
                    (
                        ( Distance__c != 0.0 and Distance__c != null) or 
                        (Hours__c != 0.0 and Hours__c != null and Task_Time__r.pse__Timecard__r.pse__Bill_Rate__c > 0) or 
                        (Days__c != 0.0 and Days__c != null and Task_Time__r.pse__Timecard__r.pse__Bill_Rate__c > 0) or 
                        (
                            Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Region__r.BU_Code__c = 'JVS' and 
                            Hours__c != 0.0 and Hours__c != null and 
                            Task_Time__r.pse__Timecard__r.pse__Billable__c = true and
                            Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Billing_Type__c in ('Subscription','Fixed Price')
                        ) or 
                        Per_Diem__c = true
                    )
                Limit
                    :MAX_RECORDS] )
            {
                TimeEntry entry = new TimeEntry( split );
                timeEntries.add( entry );
            }

            RestAPIHelper.SetRestReturn( timeEntries, false );
        }
        catch( Exception ex )
        {
            RestAPIHelper.SetRestError( 400, 'BAD_REQUEST', new List<string>{ ex.getMessage() } );
            Database.rollback( savePoint );
        }
    }
}