unpackaged/main/default/objects/pse__Proj__c/pse__Proj__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__ProjectHelp</customHelpPage>
    <description>Represents a collection of business transactions, activities, and related items to be managed over a defined time range, such as timecards, expenses, milestones, and budgets. Typically, people (represented by Resource records) are assigned to projects, though some projects do not require assignments in order to be staffed. Projects may also have a master project (parent) or a sub project (child) in the project hierarchy, supporting roll-ups of revenues, costs, and time to every project and up through the hierarchy.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/pse__Proj__c/fields/Project_Sub_Types__c.field-meta.xml
<CustomField>
    <fullName>Project_Sub_Types__c</fullName>
    <label>Project Sub-Types</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>pse__Project_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSS - Implementation</fullName>
            </value>
            <value>
                <fullName>NSS - Reference Implementation</fullName>
            </value>
            <value>
                <fullName>IBS - Upgrade</fullName>
            </value>
            <value>
                <fullName>IBS - Enhancement</fullName>
            </value>
            <value>
                <fullName>IBS - Ongoing Work</fullName>
            </value>
            <value>
                <fullName>IBS - Cloud Migration</fullName>
            </value>
            <value>
                <fullName>IBS - Subscription Managed Services</fullName>
            </value>
            <value>
                <fullName>PS Subscription - Managed Services</fullName>
            </value>
            <value>
                <fullName>PS Subscription - Forterro Service Points</fullName>
            </value>
            <value>
                <fullName>PS Subscription - Customisation Maintenance</fullName>
            </value>
            <value>
                <fullName>Internal - Business Development</fullName>
            </value>
            <value>
                <fullName>Internal - Packaged Solutions</fullName>
            </value>
            <value>
                <fullName>Internal - Field Innovation</fullName>
            </value>
            <value>
                <fullName>Internal - Organisational Development</fullName>
            </value>
            <value>
                <fullName>Internal - Administration</fullName>
            </value>
            <value>
                <fullName>Internal – Cross-Functional Work</fullName>
            </value>
            <value>
                <fullName>Internal – Unavailability</fullName>
            </value>
            <value>
                <fullName>IBS – Upgrade</fullName>
                <isActive>false</isActive>
                <label>IBS – Upgrade</label>
            </value>
            <value>
                <fullName>Internal - Cross-Functional Work</fullName>
                <isActive>false</isActive>
                <label>Internal - Cross-Functional Work</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Is_Template__c.field-meta.xml
<CustomField>
    <fullName>pse__Is_Template__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Template</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Region__c.field-meta.xml
<CustomField>
    <fullName>pse__Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>pse__Region__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/pse__Proj__c/fields/pse__Stage__c.field-meta.xml
<CustomField>
    <fullName>pse__Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/pse__Region__c/pse__Region__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__RegionHelp</customHelpPage>
    <description>An entity that represents a geographic area in which you do business. Regions are organized as an independent hierarchy determined by the Parent Region field, with parent and child records of the same type. Every region in the hierarchy may contain projects, resources (contacts), and other objects. The hierarchy allows roll-ups of revenue, cost, and time totals.</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/GetExtProjectForRegion.cls
public class GetExtProjectForRegion 
{
    public class InputParameters
    {
        @InvocableVariable(label='Region ID' required=true)
        public Id regionId;
    }

    public class OutputParameters
    {
        @InvocableVariable(label='A returned list of project IDs if found')
        public List<Id> projectIds = new List<Id>();
    }

    @InvocableMethod(callout=true label='Get EXT project for region')
    public static List<OutputParameters> getProjectForRegion( List<InputParameters> inputs )
    {
        List<OutputParameters> outputs = new List<OutputParameters>();

        // we want regions and all their parents, not interested in children
        Set<Id> regionIds = new Set<Id>();
        for( InputParameters input : inputs )
        {
            regionIds.add( input.regionId );
        }

        Map<Id,pse__Region__c> regions = new Map<Id,pse__Region__c>();

        while( regionIds.size() > 0 )
        {
            Set<Id> nextRegionIds = new Set<Id>();
            for( pse__Region__c region :
                [Select 
                    Id, 
                    pse__Parent_Region__c 
                from 
                    pse__Region__c 
                where 
                    Id in :regionIds] )
            {
                regions.put( region.Id, region );
                if( region.pse__Parent_Region__c != null )
                {
                    nextRegionIds.add( region.pse__Parent_Region__c );
                }
            }

            regionIds = nextRegionIds;
        }

        Map<Id,Set<Id>> regionIdToProjectIds = new Map<Id,Set<Id>>();

        for( pse__Proj__c project : 
            [Select 
                Id,
                pse__Region__c 
            from 
                pse__Proj__c 
            where 
                Name like '%(EXT)%' and 
                pse__Is_Active__c = true and 
                pse__Is_Template__c = false and 
                Project_Sub_Types__c = 'IBS - Enhancement' and
                pse__Stage__c = 'In Progress' and
                pse__Region__c in :regions.keySet()] )
        {
            if( !regionIdToProjectIds.containsKey( project.pse__Region__c ) )
            {
                regionIdToProjectIds.put( project.pse__Region__c, new Set<Id>() );
            }
            regionIdToProjectIds.get( project.pse__Region__c ).add( project.Id );
        }
        
        for( InputParameters input : inputs )
        {
            OutputParameters output = new OutputParameters();

            Id regionId = input.regionId;
            while( regions.containsKey( regionId ) )
            {
                pse__Region__c region = regions.get( regionId );
                if( regionIdToProjectIds.containsKey( region.Id ) )
                {
                    output.projectIds = new List<Id>( regionIdToProjectIds.get( region.Id ) );
                    break;
                }

                regionId = region.pse__Parent_Region__c;
            }

            outputs.add( output );
        }

        return outputs;
    }
}