unpackaged/main/default/objects/pse__Task_Time__c/pse__Task_Time__c.object-meta.xml
<CustomObject>
    <customHelpPage>pse__TaskTimeHelp</customHelpPage>
    <description>Records time entered against project tasks on the Time Entry page and associates project tasks with timecards.</description>
    <label>Task Time</label>
    <nameField>
        <displayFormat>TaskTime-{000000}</displayFormat>
        <label>Task Time Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Time</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Task_Time_Split__c/Task_Time_Split__c.object-meta.xml
<CustomObject>
    <description>Splits task times down to a per-day basis</description>
    <label>Task Time Split</label>
    <nameField>
        <displayFormat>TaskTimeSplit-{000000}</displayFormat>
        <label>Task Time Split Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Time Splits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Task_Time_Split__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>ERP Error Message.</description>
    <label>ErrorMessage</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Extracted</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Failed Sync</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Pending Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/fields/SyncDate__c.field-meta.xml
<CustomField>
    <fullName>SyncDate__c</fullName>
    <description>Date and Time of the ERP SYNC.</description>
    <label>SyncDate</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Task_Time_Split__c/fields/Task_Time__c.field-meta.xml
<CustomField>
    <fullName>Task_Time__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Time</label>
    <referenceTo>pse__Task_Time__c</referenceTo>
    <relationshipLabel>Task Time Splits</relationshipLabel>
    <relationshipName>Task_Time_Splits</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TaskTimeTestAPI.cls
@RestResource(urlMapping='/tasktimeapi/tasktimetest/resetsplits/*')
global with sharing class TaskTimeTestAPI 
{
    @HttpPost
    global static void HandlePost( string BUCode )
    {
        List<Task_Time_Split__c> splits = [Select Id, Sync_Status__c, SyncDate__c, ErrorMessage__c from Task_Time_Split__c where
            Task_Time__r.pse__Timecard__r.pse__Project__r.pse__Region__r.BU_Code__c = :BUCode and Sync_Status__c != 'New'];

        for( Task_Time_Split__c split : splits )
        {
            split.Sync_Status__c = 'New';
            split.SyncDate__c = null;
            split.ErrorMessage__c = '';
        }

        update splits;

        RestAPIHelper.SetRestReturn( splits.size(), true );
    }
}